// @rozie-cross-rozie-shim
// Auto-generated by @rozie/unplugin's prebuild for the Angular target.
// Re-export shim so TypeScript module resolution can find
// cross-rozie composition imports (e.g. `import { Column } from './Column'`).
// Safe to delete — will be re-emitted by the unplugin's prebuild hook.
export * from './Column.rozie';
export { default } from './Column.rozie';
