// AUTO-GENERATED by packages/ui/codemirror/scripts/codegen.mjs — DO NOT EDIT.
//
// Curated, importable CodeMirror 6 language presets for @rozie-ui/codemirror-<fw>.
// Each preset is a ready-to-spread `Extension[]` you drop into the component's
// `:extensions` for a robust syntax-highlighting starting point — with ZERO
// bloat to the base `CodeMirror` import. CM language constructors are pure (no
// global registration), so these eager exports tree-shake: importing one preset
// pulls only its own `@codemirror/lang-*` package, never the others.
//
//   import { CodeMirror } from '@rozie-ui/codemirror-<fw>';
//   import { web } from '@rozie-ui/codemirror-<fw>/languages';
//   // <CodeMirror :extensions={web} />   // HTML + embedded CSS/JS
//
// This module is FRAMEWORK-AGNOSTIC (identical across all 6 leaves) and PURELY
// ADDITIVE — the base component + its `language` prop are unchanged.
import type { Extension } from '@codemirror/state';
import { html } from '@codemirror/lang-html';
import { css } from '@codemirror/lang-css';
import { sass } from '@codemirror/lang-sass';
import { vue } from '@codemirror/lang-vue';
import { javascript } from '@codemirror/lang-javascript';
import { json } from '@codemirror/lang-json';
import { markdown } from '@codemirror/lang-markdown';
import { yaml } from '@codemirror/lang-yaml';
import { xml } from '@codemirror/lang-xml';
import { python } from '@codemirror/lang-python';
import { sql } from '@codemirror/lang-sql';

// Each constructor call is annotated `/*#__PURE__*/` so that bundlers treat the
// eager preset construction as side-effect-free and DROP any preset a consumer
// does not import. Without this annotation a bundler conservatively keeps every
// `<lang>()` call (a top-level call it cannot prove pure), pulling EVERY
// `@codemirror/lang-*` into the consumer bundle — defeating the whole design.
// (Proven empirically: importing only `web` drops lang-python/lang-sql/lang-yaml.)

// ─── Markup / web ────────────────────────────────────────────────────────────
/** HTML with auto-embedded CSS + JavaScript highlighting (the common web case). */
export const web: Extension[] = [/*#__PURE__*/ html()];
/** Alias of {@link web} — HTML + embedded CSS/JS. */
export const html_: Extension[] = web;
export { html_ as html };
/** Plain CSS. */
export const css_: Extension[] = [/*#__PURE__*/ css()];
export { css_ as css };
/** SCSS (`sass({ indented: false })`). */
export const scss: Extension[] = [/*#__PURE__*/ sass({ indented: false })];
/** Indented Sass syntax (`sass({ indented: true })`). */
export const sass_: Extension[] = [/*#__PURE__*/ sass({ indented: true })];
export { sass_ as sass };
/** Vue SFC + SCSS for `<style lang="scss">` blocks. */
export const vue_: Extension[] = [/*#__PURE__*/ vue(), /*#__PURE__*/ sass({ indented: false })];
export { vue_ as vue };

// ─── JS family ───────────────────────────────────────────────────────────────
/** JavaScript. */
export const javascript_: Extension[] = [/*#__PURE__*/ javascript()];
export { javascript_ as javascript };
/** TypeScript. */
export const typescript: Extension[] = [/*#__PURE__*/ javascript({ typescript: true })];
/** JSX (JavaScript + JSX). */
export const jsx: Extension[] = [/*#__PURE__*/ javascript({ jsx: true })];
/** TSX (TypeScript + JSX). */
export const tsx: Extension[] = [/*#__PURE__*/ javascript({ jsx: true, typescript: true })];

// ─── Data / config / prose ───────────────────────────────────────────────────
/** JSON. */
export const json_: Extension[] = [/*#__PURE__*/ json()];
export { json_ as json };
/** Markdown. */
export const markdown_: Extension[] = [/*#__PURE__*/ markdown()];
export { markdown_ as markdown };
/** YAML. */
export const yaml_: Extension[] = [/*#__PURE__*/ yaml()];
export { yaml_ as yaml };
/** XML. */
export const xml_: Extension[] = [/*#__PURE__*/ xml()];
export { xml_ as xml };
/** Python. */
export const python_: Extension[] = [/*#__PURE__*/ python()];
export { python_ as python };
/** SQL. */
export const sql_: Extension[] = [/*#__PURE__*/ sql()];
export { sql_ as sql };

// ─── Raw constructors (power users) ──────────────────────────────────────────
/**
 * The raw `@codemirror/lang-*` constructors, for composing your own extension
 * arrays (e.g. `[...lang.html(), myExtension]`). Namespaced to avoid colliding
 * with the same-named presets above. Tree-shakable: never reference `lang` and
 * the whole object is dropped.
 */
export const lang = {
  html,
  css,
  sass,
  vue,
  javascript,
  json,
  markdown,
  yaml,
  xml,
  python,
  sql,
} as const;
