/**
 * @rozie/unplugin — Phase 22 Plan 22-05: `.d.rozie.ts` sidecar generation.
 *
 * A `<Name>.d.rozie.ts` sidecar is the per-module declaration file that gives a
 * consumer's `tsc` real types for `import Foo from './Foo.rozie'` (SPEC-R5/R6).
 * It is written next to the `.rozie` source so the consumer's
 * `allowArbitraryExtensions: true` resolver honors it (per the Wave-0
 * SPIKE-FINDINGS verdict for vue/svelte/angular).
 *
 * This module owns TWO surfaces:
 *
 *   1. `renderSidecar(source, target, filename)` — PURE (no fs, no Vite). Runs
 *      parse → lowerToIR, bails on error-level diagnostics (we NEVER write a
 *      sidecar for a broken source — a stale-but-valid sidecar is safer than a
 *      type-lying one for a file that doesn't compile), dispatches on `target`
 *      to the matching `emit<Target>Types` renderer (the Wave-2/Wave-3
 *      contract), and prepends a do-not-edit + sha256 content-hash header. The
 *      CLI fallback (`rozie build`/`watch`) imports THIS so the unplugin and
 *      CLI sidecar bytes cannot drift.
 *
 *   2. `emitSidecar(roziePath, sourceText, target, allowedRoots)` — the WRITER.
 *      Computes `<Name>.d.rozie.ts` (NEVER `.rozie.d.ts`), reuses the EXACT
 *      trust-boundary posture from `emitRozieTsToDisk` (transform.ts) —
 *      null-byte guard + `allowedRoots.some(...)` outside-root refusal — and
 *      the idempotent `existsSync && existing === content` skip so a no-op
 *      re-emit doesn't trigger an HMR/chokidar write loop (T-22-05-03).
 *
 * ── ANGULAR EXCEPTION (post-22 regression fix; REVERSES the Plan-04 LOCKED
 * decision) ──────────────────────────────────────────────────────────────────
 * The writer NEVER writes a sidecar next to a `.rozie` source for
 * `target: 'angular'` — it instead DELETES any stale one it finds (heal).
 *
 * Why: TypeScript module resolution tries the arbitrary-extension declaration
 * file `<Name>.d.rozie.ts` BEFORE extension-appending finds the disk-cache
 * implementation `<Name>.rozie.ts` (and it does so regardless of
 * `allowArbitraryExtensions` — the flag only gates whether plain tsc reports an
 * error for the resolution, not whether it happens). Angular is the one target
 * that runs a TS program INSIDE the bundler: ngtsc (via
 * @analogjs/vite-plugin-angular) uses that same resolution to validate every
 * entry of a standalone component's `imports: [...]`. A type-only
 * `declare class` carries no `ɵcmp`/`ɵɵComponentDeclaration` metadata, so ngtsc
 * rejects it as a component and SILENTLY SKIPS AOT for every class that imports
 * a `.rozie` module → those classes ship raw decorators → runtime
 * "JIT compiler unavailable" (the 2026-06-02 Angular matrix + VR matrix
 * regression). The Plan 22-01 spike validated sidecar/disk-cache coexistence
 * under plain tsc only and missed this ngtsc path.
 *
 * The disk-cache `<Name>.rozie.ts` IS the typed import surface for Angular (a
 * real, fully-typed component class). A future ngtsc-valid sidecar (one that
 * declares `static ɵcmp: ɵɵComponentDeclaration<...>`, the way compiled Angular
 * libraries do) may restore named `<Name>Props` exports for Angular — until
 * then, no `.d.rozie.ts` may sit next to a `.rozie` an Angular build consumes.
 *
 * `renderSidecar` itself still supports `target: 'angular'`: the CLI
 * (`rozie build`/`watch`) writes Angular sidecars next to its OUTPUT files
 * (compiled `.ts`, no `.rozie` siblings), where the shadowing hazard cannot
 * arise.
 *
 * @experimental — shape may change before v1.0
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { isAbsolute, relative as pathRelative } from 'node:path';
import { parse } from '../../core/src/parse.js';
import { lowerToIR } from '../../core/src/ir/lower.js';
import { ModifierRegistry } from '@rozie/core';
import { registerBuiltins } from '../../core/src/modifiers/registerBuiltins.js';
import { emitReactTypes } from '../../targets/react/src/emit/emitTypes.js';
import { emitVueTypes } from '../../targets/vue/src/emit/emitTypes.js';
import { emitSvelteTypes } from '../../targets/svelte/src/emit/emitTypes.js';
import { emitSolidTypes } from '../../targets/solid/src/emit/emitTypes.js';
import { emitLitTypes } from '../../targets/lit/src/emit/emitTypes.js';
import { emitAngularTypes } from '../../targets/angular/src/emit/emitTypes.js';
import type { TargetValue } from './options.js';

/**
 * The exact do-not-edit header prefix (sans the 12-char hash + newline). The
 * staleness gate (Plan 06) re-hashes the source and string-compares the hash
 * suffix; keep this constant the single source of truth for both writer and
 * verifier.
 */
export const SIDECAR_HEADER_PREFIX =
  '// AUTO-GENERATED by @rozie/unplugin — do not edit. source-hash: ';

/**
 * Compute the deterministic 12-hex content hash of a `.rozie` source — the
 * integrity signal embedded in every sidecar header (REQ-6 / T-22-05-02).
 */
export function sidecarSourceHash(source: string): string {
  return createHash('sha256').update(source).digest('hex').slice(0, 12);
}

// A single shared modifier registry — lowerToIR needs one; sidecar rendering
// never mutates it after registerBuiltins, so a module-level singleton is safe
// and avoids re-registering builtins on every `.rozie` in a project scan.
let sharedRegistry: ModifierRegistry | null = null;
function getRegistry(): ModifierRegistry {
  if (sharedRegistry === null) {
    sharedRegistry = new ModifierRegistry();
    registerBuiltins(sharedRegistry);
  }
  return sharedRegistry;
}

/**
 * Dispatch on `target` to the matching `emit<Target>Types` renderer. The five
 * non-React renderers (Plan 03/04) + React (existing) all consume the
 * Plan-02 core-shared `renderPropsInterface`, so the prop/event/slot mapping
 * is single-source and cannot drift across targets.
 */
function renderTypesFor(
  target: TargetValue,
  // biome-ignore lint/suspicious/noExplicitAny: IRComponent flows through the per-target renderer signatures
  ir: any,
): string {
  switch (target) {
    case 'react':
      return emitReactTypes(ir);
    case 'vue':
      return emitVueTypes(ir);
    case 'svelte':
      return emitSvelteTypes(ir);
    case 'solid':
      return emitSolidTypes(ir);
    case 'lit':
      return emitLitTypes(ir);
    case 'angular':
      // NOTE: kept for the CLI path only (sidecars next to compiled OUTPUT
      // files). `emitSidecar` below refuses to place an Angular sidecar next to
      // a `.rozie` source — see the ANGULAR EXCEPTION block in the module doc.
      return emitAngularTypes(ir);
    default: {
      // Exhaustiveness guard — a new target must extend this switch.
      const _never: never = target;
      throw new Error(`@rozie/unplugin: no sidecar renderer for target ${String(_never)}`);
    }
  }
}

/**
 * PURE render: `.rozie` source → full `.d.rozie.ts` text (header + per-target
 * body), or `null` when the source has error-level parse/lowering diagnostics.
 *
 * No filesystem, no Vite — safe to import from the CLI fallback so the unplugin
 * and CLI sidecar bytes are identical.
 */
export function renderSidecar(
  source: string,
  target: TargetValue,
  filename: string,
): string | null {
  const { ast, diagnostics: parseDiags } = parse(source, { filename });
  if (!ast || parseDiags.some((d) => d.severity === 'error')) return null;

  const { ir, diagnostics: irDiags } = lowerToIR(ast, { modifierRegistry: getRegistry() });
  if (!ir || irDiags.some((d) => d.severity === 'error')) return null;

  // Phase 38 — ROZ088 portal-scoped-style is intentionally NOT run here. The
  // sidecar path is a type-declaration render (`renderTypesFor`) that does not
  // call `threadParamTypes`, so `filler.isPortal` is never populated and the
  // pass would warn on nothing. The diagnostic fires on the emit pipelines
  // (transform.ts, which threads first) and in `compile()` — this `.d.rozie.ts`
  // generation path neither emits CSS nor surfaces warnings to the build.
  const body = renderTypesFor(target, ir);
  const header = `${SIDECAR_HEADER_PREFIX}${sidecarSourceHash(source)}\n`;
  return header + body + (body.endsWith('\n') ? '' : '\n');
}

/**
 * Refuse paths whose null byte / outside-root would let a malicious `.rozie`
 * path escape the project tree on write (T-22-05-01). Mirrors the
 * `emitRozieTsToDisk` posture: null-byte guard + `allowedRoots.some(...)`.
 */
function assertWritable(roziePath: string, allowedRoots: readonly string[]): void {
  if (roziePath.includes('\0')) {
    throw new Error(
      `@rozie/unplugin: refusing to write sidecar for path with null byte: ${JSON.stringify(roziePath)}`,
    );
  }
  if (allowedRoots.length === 0) return; // unscoped (tests / direct callers)
  const allowed = allowedRoots.some((root) => {
    const rel = pathRelative(root, roziePath);
    return !rel.startsWith('..') && !isAbsolute(rel);
  });
  if (!allowed) {
    throw new Error(
      `@rozie/unplugin: refusing to write .d.rozie.ts sidecar outside any allowed root: ${roziePath} (allowed: ${allowedRoots.join(', ')})`,
    );
  }
}

/**
 * Render + write a `<Name>.d.rozie.ts` sidecar next to its `.rozie` source.
 *
 * @returns the written sidecar path, or `null` when the source bailed on
 *   diagnostics (no sidecar for a broken source), the target is `'angular'`
 *   (ANGULAR EXCEPTION — heal + skip, see module doc), OR the write was an
 *   idempotent skip (content unchanged) — in the skip case the path string the
 *   caller would have written is returned so callers can log/track it
 *   consistently.
 *
 *   NOTE on the skip return: an idempotent skip returns the SAME `outPath`
 *   string as a fresh write (the file is already correct on disk); only the
 *   diagnostics-bail path returns `null`. This matches `emitRozieTsToDisk`,
 *   which returns the path on both write and skip.
 */
export function emitSidecar(
  roziePath: string,
  sourceText: string,
  target: TargetValue,
  allowedRoots: readonly string[],
): string | null {
  // Trust boundary FIRST — refuse an out-of-root / null-byte path before any
  // render work (and so the null-byte test never reaches the `.replace`).
  assertWritable(roziePath, allowedRoots);

  // ANGULAR EXCEPTION (see module doc): never place a type-only `.d.rozie.ts`
  // next to a `.rozie` an Angular build consumes — ngtsc's module resolution
  // prefers it over the disk-cache `.rozie.ts` value class, killing AOT
  // ("JIT compiler unavailable"). HEAL instead: delete any stale sidecar a
  // pre-fix build (or a different-target build over a shared tree) left behind,
  // then bail. Deletion failures propagate (the buildStart walker aggregates
  // them via WR-04).
  if (target === 'angular') {
    const stalePath = roziePath.replace(/\.rozie$/, '.d.rozie.ts');
    if (existsSync(stalePath)) {
      unlinkSync(stalePath);
      // biome-ignore lint/suspicious/noConsole: build-time heal diagnostic
      console.warn(
        `[@rozie/unplugin] removed stale Angular sidecar ${stalePath} (a .d.rozie.ts next to a .rozie source breaks ngtsc AOT — see emitSidecar.ts ANGULAR EXCEPTION)`,
      );
    }
    return null;
  }

  const content = renderSidecar(sourceText, target, roziePath);
  if (content === null) return null; // broken source — never write a type-lie

  // Anti-Pattern guard (plan): the sidecar is `<Name>.d.rozie.ts`, NEVER
  // `<Name>.rozie.d.ts`. `allowArbitraryExtensions` resolves `./Foo.rozie` to
  // `Foo.d.rozie.ts` (the `.d.<ext>.ts` form); `.rozie.d.ts` would NOT be
  // honored.
  const outPath = roziePath.replace(/\.rozie$/, '.d.rozie.ts');

  // Idempotent skip — no rewrite when byte-identical (T-22-05-03: prevents an
  // HMR/chokidar write loop). Mirrors emitRozieTsToDisk.
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, 'utf8');
    if (existing === content) return outPath;
  }
  writeFileSync(outPath, content, 'utf8');
  return outPath;
}
