// @vitest-environment happy-dom
/**
 * timers.behavior.test.ts — mount-and-drive behavioral proof for the precise
 * remaining-time hover pause (TOAST-PAUSE).
 *
 * Mirrors combobox's tests/seed-query.behavior.test.ts precedent: mount the
 * REAL committed emitted packages/vue/src/Toaster.vue (transformed by
 * @vitejs/plugin-vue), obtain the `$expose`d handle via a template ref, drive
 * it with `vi.useFakeTimers()` (mocks both `setTimeout` and `Date.now`, which
 * the source's `startedAt`/`remaining` bookkeeping reads), and assert on the
 * rendered `[role="status"]` toast count — the only way to catch a
 * runtime-semantic regression (typechecks clean, wrong behavior) rather than
 * a text/AST assertion.
 *
 * RED-FIRST: run against the CURRENT (un-regenerated) leaf — `pauseTimers`
 * deletes entries and `onMouseLeave` restarts the FULL duration, so a
 * 1000ms toast hovered at ~600ms and released survives ~1000ms after leave,
 * not the ~400ms remainder. The "dismisses at the remainder, not the full
 * duration" assertion below FAILS on that leaf. GREEN only after the source
 * rework (timers map → `{handle,startedAt,remaining}`, `pauseTimers`
 * decrements+keeps, `resumeTimers` re-arms the remainder) + `node
 * scripts/codegen.mjs` regenerates the Vue leaf.
 */
import { describe, it, expect, afterEach, beforeEach, vi } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Toaster.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Toaster from '../../packages/vue/src/Toaster.vue';

interface ToasterHandle {
  show: (input?: Record<string, unknown>) => string;
  dismiss: (id: string) => void;
  clear: () => void;
}

const hosts: HTMLElement[] = [];

beforeEach(() => {
  vi.useFakeTimers();
});

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
  vi.useRealTimers();
});

/**
 * Mount Toaster with a template ref to the `$expose` handle, returning the
 * host element and the handle itself.
 */
function mountToaster(props: Record<string, unknown> = {}) {
  const handleRef = ref<ToasterHandle | null>(null);
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Toaster, {
        ref: handleRef,
        position: 'bottom-right',
        ...props,
      }),
  });
  app.mount(host);
  return { app, host, handle: () => handleRef.value as ToasterHandle };
}

function statusCount(host: HTMLElement): number {
  return host.querySelectorAll('[role="status"]').length;
}

describe('Toaster hover pause — precise remaining-time (behavioral)', () => {
  it('dismisses ~400ms after leave (the remainder), NOT ~1000ms (the v1 full-restart shortcut)', async () => {
    const { app, host, handle } = mountToaster();

    handle().show({ message: 'Saved', type: 'success', duration: 1000 });
    await nextTick();
    expect(statusCount(host)).toBe(1);

    // Elapse ~600ms of the 1000ms duration, then hover (pause).
    await vi.advanceTimersByTimeAsync(600);
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();

    // Hovered well past the ORIGINAL 1000ms total — must still be present
    // (paused, not just delayed by the browser's timer granularity).
    await vi.advanceTimersByTimeAsync(1000);
    expect(statusCount(host)).toBe(1);

    // Leave — resume with EXACTLY the ~400ms remainder.
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseleave'));
    await nextTick();

    // Just under the remainder — still present.
    await vi.advanceTimersByTimeAsync(390);
    expect(statusCount(host)).toBe(1);

    // Past the remainder (~400ms since leave, not ~1000ms) — the exit
    // lifecycle begins, then settles via the ~350ms failsafe (happy-dom never
    // fires a real animationend). Total elapsed since leave (~770ms) stays
    // well under what the old v1 full-restart shortcut would have needed
    // (~1000ms + the failsafe) — proving the PRECISE remainder, not a reset.
    await vi.advanceTimersByTimeAsync(20);
    await nextTick();
    await vi.advanceTimersByTimeAsync(360);
    await nextTick();
    expect(statusCount(host)).toBe(0);

    app.unmount();
  });

  it('sticky toasts (duration <= 0) never enter the timers map — hover is a no-op for them', async () => {
    const { app, host, handle } = mountToaster();

    handle().show({ message: 'Sticky', type: 'info', duration: 0 });
    await nextTick();
    expect(statusCount(host)).toBe(1);

    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseleave'));
    await nextTick();

    await vi.advanceTimersByTimeAsync(10_000);
    expect(statusCount(host)).toBe(1);

    app.unmount();
  });

  it('disablePauseOnHover short-circuits both hover handlers (unchanged)', async () => {
    const { app, host, handle } = mountToaster({ disablePauseOnHover: true });

    handle().show({ message: 'Saved', type: 'success', duration: 1000 });
    await nextTick();

    await vi.advanceTimersByTimeAsync(600);
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();

    // disablePauseOnHover=true: hover does NOT pause — the toast still
    // dismisses at the ORIGINAL full duration regardless of the hover, then
    // settles via the ~350ms exit failsafe.
    await vi.advanceTimersByTimeAsync(400);
    await nextTick();
    await vi.advanceTimersByTimeAsync(360);
    await nextTick();
    expect(statusCount(host)).toBe(0);

    app.unmount();
  });

  it('clear() fully tears down every timer — no dismissal fires after clear() even as fake time advances', async () => {
    const { app, host, handle } = mountToaster();

    handle().show({ message: 'a', duration: 1000 });
    handle().show({ message: 'b', duration: 2000 });
    await nextTick();
    expect(statusCount(host)).toBe(2);

    handle().clear();
    await nextTick();
    expect(statusCount(host)).toBe(0);

    // No leaked handle throws or re-adds anything as fake time runs out.
    await vi.advanceTimersByTimeAsync(5000);
    await nextTick();
    expect(statusCount(host)).toBe(0);

    app.unmount();
  });

  it('$onUnmount tears down every timer (no leaked handle after unmount)', async () => {
    const { app, host, handle } = mountToaster();

    handle().show({ message: 'a', duration: 1000 });
    await nextTick();
    expect(statusCount(host)).toBe(1);

    app.unmount();

    // Must not throw even though the component instance is gone (a leaked
    // handle firing dismiss() post-unmount would blow up here).
    let threw = false;
    try {
      await vi.advanceTimersByTimeAsync(5000);
    } catch {
      threw = true;
    }
    expect(threw).toBe(false);
  });
});

describe('Toaster numeric consumer id — survives a hover cycle (T3, behavioral)', () => {
  // RED-FIRST: the timers map is keyed by `for (const id in timers)`, which
  // yields STRING keys; `resumeTimers` re-arms `dismissBegin(id, 'timeout')`
  // with that string, but a consumer-supplied NUMERIC id (`show({ id: 42 })`)
  // stored the toast's `id` as the number 42, so `dismissBegin`'s
  // `$data.toasts.find(t => t.id === '42')` strict-compares number-vs-string
  // and never matches → the toast is stranded after the hover pause/resume.
  // GREEN only once show() coerces `id = String(t.id)` so every id is a string
  // end-to-end.
  it('show({ id: 42 }) still auto-dismisses after hover → leave', async () => {
    const { app, host, handle } = mountToaster();

    handle().show({ id: 42, message: 'numbered', type: 'info', duration: 1000 });
    await nextTick();
    expect(statusCount(host)).toBe(1);

    // Hover partway through → pause.
    await vi.advanceTimersByTimeAsync(300);
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();
    await vi.advanceTimersByTimeAsync(3000);
    expect(statusCount(host)).toBe(1); // paused, still present

    // Leave → resume with the ~700ms remainder, which must dismiss id 42.
    host.querySelector('.rozie-toaster')!.dispatchEvent(new MouseEvent('mouseleave'));
    await nextTick();
    await vi.advanceTimersByTimeAsync(700);
    await nextTick();
    await vi.advanceTimersByTimeAsync(360); // exit failsafe
    await nextTick();
    expect(statusCount(host)).toBe(0);

    app.unmount();
  });
});

describe('Toaster pauseTimers idempotency — no negative-remainder strand (T1, behavioral)', () => {
  // RED-FIRST: pauseTimers was NOT idempotent — a second pause on an
  // already-paused entry re-subtracted the elapsed time against the ORIGINAL
  // (unchanged) startedAt, driving `remaining` negative; resumeTimers then
  // saw `remaining <= 0` and skipped it FOREVER (never re-armed, never
  // dismissed) → the toast was stranded. The fix makes pauseTimers skip
  // entries whose handle is already null (idempotent) AND clamp
  // `remaining = Math.max(0, …)`, and makes resumeTimers treat a non-positive
  // remainder as EXPIRED (dismiss now, matching "its time elapsed") rather
  // than skipping.
  it('a double pause (with wall-clock between) still dismisses on resume, never strands', async () => {
    const { app, host, handle } = mountToaster();
    const region = () => host.querySelector('.rozie-toaster')!;

    handle().show({ message: 'x', type: 'info', duration: 1000 });
    await nextTick();
    expect(statusCount(host)).toBe(1);

    // Elapse 300ms, then pause (remainder → 700ms).
    await vi.advanceTimersByTimeAsync(300);
    region().dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();

    // A LOT of wall-clock passes while paused (the timer handle is cleared so
    // nothing fires), THEN a second pause event arrives. Pre-fix, this second
    // pause computes elapsed = now - startedAt (~1100ms) against remaining
    // 700ms → remaining = -400ms, and resume skips it forever.
    await vi.advanceTimersByTimeAsync(800);
    region().dispatchEvent(new MouseEvent('mouseenter'));
    await nextTick();
    expect(statusCount(host)).toBe(1); // still paused/present

    // Leave → resume. The remainder must still be the correct positive ~700ms
    // (idempotent second pause was a no-op), so the toast dismisses.
    region().dispatchEvent(new MouseEvent('mouseleave'));
    await nextTick();
    await vi.advanceTimersByTimeAsync(700);
    await nextTick();
    await vi.advanceTimersByTimeAsync(360); // exit failsafe
    await nextTick();
    expect(statusCount(host)).toBe(0);

    app.unmount();
  });
});
