// @vitest-environment happy-dom
/**
 * creatable.behavior.test.ts — mount-and-drive behavioral proof for the
 * `creatable` prop (Phase 86 R3, plan 86-06): a `creatable: Boolean` prop, a
 * navigable create row rendered last in every render branch, and a
 * consumer-owned `create` event that lets arbitrary typed text become a
 * selection without combobox ever guessing the consumer's option shape.
 *
 * Mirrors multiple.behavior.test.ts (itself the seed-query/captcha
 * model-param-shadow.vue.test.ts precedent): mount the REAL committed
 * emitted packages/vue/src/Combobox.vue (transformed by @vitejs/plugin-vue),
 * drive it via real DOM events, and assert on the rendered DOM + the
 * collected `create` events.
 *
 * Task 1 (this initial slice, red-first against the source BEFORE the
 * `creatable` prop/emit/row existed — see the SUMMARY for the captured
 * failing output) proves the core mechanics on the plain (ungrouped,
 * non-virtual) branch only. Task 2 expands this file into the full
 * seven-behavior-group × four-render-branch matrix R3 requires.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
];

const hosts: HTMLElement[] = [];
afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

function mountCombobox(extraProps: Record<string, unknown> = {}) {
  const value = ref<unknown>(null);
  const creates: Array<Record<string, unknown>> = [];
  const changes: unknown[] = [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: unknown) => {
          value.value = v;
        },
        onChange: (e: unknown) => changes.push(e),
        onCreate: (e: Record<string, unknown>) => creates.push(e),
        options: OPTIONS,
        creatable: true,
        placeholder: 'Search fruit…',
        ariaLabel: 'Fruit',
        idBase: 'creatable-test',
        ...extraProps,
      }),
  });
  app.mount(host);
  return { app, host, value: () => value.value, creates, changes };
}

async function typeQuery(host: HTMLElement, text: string): Promise<HTMLInputElement> {
  const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
  input.dispatchEvent(new Event('focus'));
  await nextTick();
  input.value = text;
  input.dispatchEvent(new Event('input'));
  await nextTick();
  return input;
}

function createRowEl(host: HTMLElement): HTMLElement | null {
  return host.querySelector('.rozie-combobox-create');
}

describe('Combobox creatable — core mechanics (behavioral, plain branch)', () => {
  it('committing unmatched text emits `create` with the query and writes NOTHING to value', async () => {
    const { app, host, value, creates } = mountCombobox();
    try {
      const input = await typeQuery(host, 'kiwi');
      const row = createRowEl(host);
      expect(row).not.toBeNull();
      expect(row!.textContent).toContain('kiwi');

      row!.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
      await nextTick();

      expect(creates).toEqual([{ query: 'kiwi' }]);
      expect(value()).toBe(null);
      void input;
    } finally {
      app.unmount();
    }
  });

  it('a query exactly matching an existing option label (any case, trimmed) offers NO create row', async () => {
    const { app, host } = mountCombobox();
    try {
      await typeQuery(host, 'APPLE');
      expect(createRowEl(host)).toBeNull();

      await typeQuery(host, '  apple  ');
      expect(createRowEl(host)).toBeNull();
    } finally {
      app.unmount();
    }
  });

  it('an empty or whitespace-only query offers NO create row', async () => {
    const { app, host } = mountCombobox();
    try {
      await typeQuery(host, '');
      expect(createRowEl(host)).toBeNull();

      await typeQuery(host, '   ');
      expect(createRowEl(host)).toBeNull();
    } finally {
      app.unmount();
    }
  });

  it('a double-commit gesture on the same query emits `create` exactly once', async () => {
    const { app, host, creates } = mountCombobox();
    try {
      await typeQuery(host, 'kiwi');
      let row = createRowEl(host);
      row!.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
      await nextTick();
      // Re-open the popup: closeOnSelect default (true, single-select) closed
      // it, but the query text is unchanged in single mode, so the same
      // creatable row is offered again on refocus.
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      row = createRowEl(host);
      expect(row).not.toBeNull();
      row!.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
      await nextTick();

      expect(creates).toEqual([{ query: 'kiwi' }]);
    } finally {
      app.unmount();
    }
  });

  it('the create row is Arrow-reachable and carries a real option id', async () => {
    const { app, host } = mountCombobox();
    try {
      const input = await typeQuery(host, 'kiwi');
      // Only the create row is navigable (no options match "kiwi").
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
      await nextTick();
      const row = createRowEl(host);
      expect(row).not.toBeNull();
      expect(row!.id).toBeTruthy();
      expect(input.getAttribute('aria-activedescendant')).toBe(row!.id);
    } finally {
      app.unmount();
    }
  });

  it('with `creatable` unset, nothing about the rendered output changes (byte-identical-off)', async () => {
    const { app, host } = mountCombobox({ creatable: false });
    try {
      await typeQuery(host, 'kiwi');
      expect(createRowEl(host)).toBeNull();
      expect(host.querySelectorAll('[role="option"]').length).toBe(0);
    } finally {
      app.unmount();
    }
  });

  it('with `multiple` also active, `create` fires and `value` stays untouched', async () => {
    const { app, host, value, creates } = mountCombobox({ multiple: true });
    try {
      const input = await typeQuery(host, 'kiwi');
      const row = createRowEl(host);
      row!.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
      await nextTick();

      expect(creates).toEqual([{ query: 'kiwi' }]);
      expect(value()).toEqual(null);
      // D-20: the query clears in multiple mode after a create commit.
      expect(input.value).toBe('');
    } finally {
      app.unmount();
    }
  });
});
