// @vitest-environment happy-dom
/**
 * floating-popover.behavior.test.ts — mount-and-drive behavioral proof for plan
 * 86-03's non-pixel R2 criteria: all four render branches now share the SAME
 * composed `@rozie-ui/popover` positioning path (plain / grouped / grouped+capped
 * / windowed), with `keepMounted` forwarded only when `virtual` (D-10) and
 * `disablePositioning` forwarded only when `inline` (D-09).
 *
 * Mirrors seed-query.behavior.test.ts / group-cap.behavior.test.ts / virtual-flip.
 * behavior.test.ts: mount the REAL committed emitted packages/vue/src/Combobox.vue
 * (transformed by @vitejs/plugin-vue — this file, never the .rozie source, is what
 * actually ships), and drive it via real DOM events.
 *
 * `autoUpdate` (the Floating UI subscription the "no leak" / "inline mounts none"
 * criteria hinge on) is imported directly by the committed emitted
 * `@rozie-ui/popover-vue` leaf from `@floating-ui/dom`. It is spied via `vi.mock`
 * (wrapping, not replacing, the real implementation) so every assertion below
 * counts REAL subscribe/teardown calls rather than guessing from visibility —
 * a popup that is merely visible does not prove the absence of a listener leak,
 * which is the criterion SPEC locks.
 *
 * Asserts (behavior list from the plan):
 *   1. inline (D-09 restated): opening the popup mounts NO `autoUpdate`
 *      subscription and writes no inline left/top onto the panel — the panel
 *      renders in normal flow.
 *   2. idempotency (SPEC R2): open → close → open leaves exactly ONE live
 *      `autoUpdate` subscription; the live count after the second open equals
 *      the live count after the first.
 *   3. empty (SPEC R2): a zero-length `options` array still mounts + positions
 *      the popup (a subscription is started) and renders the `#empty` slot.
 *   4. dismissal (D-07): a document-level Escape closes the popup exactly once
 *      and leaves the query text untouched (a single-close path, not a double
 *      close-and-clear).
 *   5. windowed unmount contract (D-10): with `virtual` set, closing leaves the
 *      windowed scroll container in the DOM (hidden, not removed — CR-01);
 *      without `virtual`, closing removes the list (and the whole composed
 *      popover wrapper) from the DOM.
 */
import { describe, it, expect, afterEach, beforeEach, vi } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';

// `vi.mock` factories are hoisted above imports — any state they close over must
// come from `vi.hoisted()`, not a plain module-scope `let` declared below.
const floatingUiState = vi.hoisted(() => ({
  autoUpdateCalls: 0,
  teardownCalls: 0,
}));

vi.mock('@floating-ui/dom', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@floating-ui/dom')>();
  return {
    ...actual,
    autoUpdate: (...args: Parameters<typeof actual.autoUpdate>) => {
      floatingUiState.autoUpdateCalls++;
      const stop = actual.autoUpdate(...args);
      return () => {
        floatingUiState.teardownCalls++;
        stop();
      };
    },
  };
});

// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs` from
// the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this SFC into
// a mountable component. Imported AFTER vi.mock so the mock is active when
// Combobox.vue's own `import Popover from '@rozie-ui/popover-vue'` (and that
// leaf's own `@floating-ui/dom` import) resolves.
import Combobox from '../packages/vue/src/Combobox.vue';

const liveAutoUpdateCount = () => floatingUiState.autoUpdateCalls - floatingUiState.teardownCalls;

const OPTIONS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
];

const hosts: HTMLElement[] = [];

beforeEach(() => {
  floatingUiState.autoUpdateCalls = 0;
  floatingUiState.teardownCalls = 0;
});

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

interface MountOpts {
  inline?: boolean;
  virtual?: boolean;
  options?: unknown[];
}

/**
 * Mount Combobox with a two-way `value` binding + a `change` spy, returning the
 * host element and the query/change accessors.
 */
function mountCombobox(opts: MountOpts = {}) {
  const value = ref<string | null>(null);
  const changes: unknown[] = [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        onChange: (e: unknown) => changes.push(e),
        options: opts.options ?? OPTIONS,
        ariaLabel: 'Fruit',
        idBase: 'floating-popover-test',
        inline: !!opts.inline,
        virtual: !!opts.virtual,
        maxHeight: opts.virtual ? '200px' : '',
      }),
  });
  app.mount(host);
  return { app, host, value: () => value.value, changes };
}

describe('Combobox floating popover — composed positioning path (behavioral, plan 86-03)', () => {
  it('(1) inline: opening mounts NO autoUpdate subscription and writes no inline left/top', async () => {
    const { app, host } = mountCombobox({ inline: true });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      // The list renders (inline is a static PASS-THROUGH, not "no popover
      // involvement" — D-09's restated criterion).
      expect(host.querySelectorAll('[role="option"]').length).toBe(4);

      // No autoUpdate subscription was ever started.
      expect(floatingUiState.autoUpdateCalls).toBe(0);

      // No inline coordinate style was written onto the floating panel.
      const panel = host.querySelector('.rozie-popover-floating') as HTMLElement | null;
      expect(panel).not.toBeNull();
      expect(panel!.style.left).toBe('');
      expect(panel!.style.top).toBe('');
    } finally {
      app.unmount();
    }
  });

  it('(2) open -> close -> open leaves exactly one live autoUpdate subscription', async () => {
    const { app, host } = mountCombobox();
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;

      // First open.
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      await Promise.resolve();
      const liveAfterFirstOpen = liveAutoUpdateCount();
      expect(liveAfterFirstOpen).toBe(1);

      // Close.
      input.dispatchEvent(new Event('blur'));
      await nextTick();
      expect(liveAutoUpdateCount()).toBe(0);

      // Second open.
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      await Promise.resolve();
      expect(liveAutoUpdateCount()).toBe(liveAfterFirstOpen);
      expect(liveAutoUpdateCount()).toBe(1);
    } finally {
      app.unmount();
    }
  });

  it('(3) an empty options array still positions the popup and renders #empty', async () => {
    const { app, host } = mountCombobox({ options: [] });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      await Promise.resolve();

      // A subscription was started — the popup positions itself even with
      // nothing to show.
      expect(liveAutoUpdateCount()).toBe(1);

      const empty = host.querySelector('.rozie-combobox-empty');
      expect(empty).not.toBeNull();
      expect(empty!.textContent).toContain('No results');
    } finally {
      app.unmount();
    }
  });

  it('(4) a document Escape closes the popup exactly once, query stays intact', async () => {
    const { app, host } = mountCombobox();
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      input.value = 'cher';
      input.dispatchEvent(new Event('input'));
      await nextTick();
      expect(input.value).toBe('cher');
      expect(host.querySelectorAll('[role="option"]').length).toBe(1);

      // Escape on the input bubbles to `document` — both combobox's OWN
      // onKeydown Escape branch AND popover's document-level dismiss listener
      // observe the SAME keydown event (D-07: both dismissal owners stay
      // active). Closing must be idempotent, not a double-toggle back open.
      input.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      );
      await nextTick();
      await Promise.resolve();

      expect(host.querySelectorAll('[role="option"]').length).toBe(0);
      // The query was never cleared by the close path (only a pick clears it).
      expect(input.value).toBe('cher');

      // A second, redundant Escape (already closed) stays closed — idempotent,
      // not a re-open.
      input.dispatchEvent(
        new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }),
      );
      await nextTick();
      expect(host.querySelectorAll('[role="option"]').length).toBe(0);
      expect(input.value).toBe('cher');
    } finally {
      app.unmount();
    }
  });

  it('(5a) virtual: closing leaves the windowed scroll container in the DOM (hidden, not removed)', async () => {
    const { app, host } = mountCombobox({ virtual: true });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      const list = host.querySelector('.rozie-combobox-list--virtual') as HTMLElement | null;
      expect(list).not.toBeNull();

      input.dispatchEvent(new Event('blur'));
      await nextTick();

      // Still present — hidden via display:none, not unmounted (CR-01).
      const listAfterClose = host.querySelector('.rozie-combobox-list--virtual') as HTMLElement | null;
      expect(listAfterClose).not.toBeNull();
      expect(listAfterClose!.style.display).toBe('none');
    } finally {
      app.unmount();
    }
  });

  it('(5b) non-virtual: closing removes the composed popover wrapper from the DOM', async () => {
    const { app, host } = mountCombobox({ virtual: false });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      expect(host.querySelector('.rozie-combobox-list')).not.toBeNull();

      input.dispatchEvent(new Event('blur'));
      await nextTick();

      // Fully unmounted — no residual list, no residual composed popover
      // floating panel either.
      expect(host.querySelector('.rozie-combobox-list')).toBeNull();
      expect(host.querySelector('.rozie-popover-floating')).toBeNull();
    } finally {
      app.unmount();
    }
  });
});
