// @vitest-environment happy-dom
/**
 * group-cap.behavior.test.ts — mount-and-drive behavioral proof for the
 * `groupCap` per-group result cap + expand-in-place "+N more" affordance
 * (combobox-group-cap).
 *
 * Mirrors keep-open.behavior.test.ts (itself the seed-query/captcha
 * model-param-shadow.vue.test.ts precedent): mount the REAL committed
 * emitted packages/vue/src/Combobox.vue (transformed by
 * @vitejs/plugin-vue), drive it via real DOM events, and assert on the
 * rendered DOM + the two-way `value` model.
 *
 * Asserts:
 *   (a) cap ON + an overflowing group: focus opens the popup, the Fruit
 *       section renders 2 options + one `.rozie-combobox-more` row whose
 *       text contains "2 more".
 *   (b) activating the more-row (mousedown) does NOT touch the value model
 *       or fire `change` — it only expands the group in place.
 *   (c) after expansion, the Fruit section shows all 4 options and the
 *       more-row is gone.
 *   (d) selecting a real option still commits `value` + fires `change`.
 *   (e) a control run with NO `groupCap` renders all options with no
 *       `.rozie-combobox-more` row (byte-identical-off).
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = [
  { value: 'apple', label: 'Apple', group: 'fruit' },
  { value: 'banana', label: 'Banana', group: 'fruit' },
  { value: 'cherry', label: 'Cherry', group: 'fruit' },
  { value: 'date', label: 'Date', group: 'fruit' },
  { value: 'carrot', label: 'Carrot', group: 'veg' },
  { value: 'potato', label: 'Potato', group: 'veg' },
];

const GROUPS = [
  { id: 'fruit', label: 'Fruit' },
  { id: 'veg', label: 'Vegetable' },
];

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount Combobox with two-way `value` binding + a `change` spy, returning
 * the host element and the change-event log.
 */
function mountCombobox(extraProps: Record<string, unknown> = {}) {
  const value = ref<string | null>(null);
  const changes: unknown[] = [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        onChange: (e: unknown) => changes.push(e),
        options: OPTIONS,
        groups: GROUPS,
        ariaLabel: 'Fruit or vegetable',
        idBase: 'group-cap-test',
        ...extraProps,
      }),
  });
  app.mount(host);
  return { app, host, changes, value: () => value.value };
}

describe('Combobox groupCap — per-group cap + expand-in-place "+N more" (behavioral)', () => {
  it('cap ON: an overflowing group renders `cap` options + one "+N more" row', async () => {
    const { app, host } = mountCombobox({ groupCap: 2 });

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();

    const groups = host.querySelectorAll('[role="group"]');
    expect(groups.length).toBe(2);

    const fruitOptions = groups[0]!.querySelectorAll('[role="option"]:not(.rozie-combobox-more)');
    expect(fruitOptions.length).toBe(2);
    expect(fruitOptions[0]!.textContent).toContain('Apple');
    expect(fruitOptions[1]!.textContent).toContain('Banana');

    const moreRow = groups[0]!.querySelector('.rozie-combobox-more');
    expect(moreRow).not.toBeNull();
    expect(moreRow!.textContent).toContain('2 more');

    // Non-overflowing Veg group (2 items, cap 2) renders no more-row.
    const vegMore = groups[1]!.querySelector('.rozie-combobox-more');
    expect(vegMore).toBeNull();
    const vegOptions = groups[1]!.querySelectorAll('[role="option"]');
    expect(vegOptions.length).toBe(2);

    app.unmount();
  });

  it('activating the more-row expands the group in place, fires NO change, touches NO value', async () => {
    const { app, host, changes, value } = mountCombobox({ groupCap: 2 });

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();

    const moreRow = host.querySelector('.rozie-combobox-more') as HTMLElement;
    expect(moreRow).not.toBeNull();
    moreRow.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
    await nextTick();

    // No commit whatsoever from activating the more-row.
    expect(changes.length).toBe(0);
    expect(value()).toBeNull();

    // The Fruit group now shows all 4 options and the more-row is gone.
    const groups = host.querySelectorAll('[role="group"]');
    const fruitOptions = groups[0]!.querySelectorAll('[role="option"]');
    expect(fruitOptions.length).toBe(4);
    expect(host.querySelectorAll('.rozie-combobox-more').length).toBe(0);

    app.unmount();
  });

  it('selecting a real option still commits value + fires change after expansion', async () => {
    const { app, host, changes, value } = mountCombobox({ groupCap: 2 });

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();

    const moreRow = host.querySelector('.rozie-combobox-more') as HTMLElement;
    moreRow.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
    await nextTick();

    const groups = host.querySelectorAll('[role="group"]');
    const dateOption = Array.from(groups[0]!.querySelectorAll('[role="option"]')).find((el) =>
      el.textContent?.includes('Date'),
    ) as HTMLElement;
    expect(dateOption).toBeTruthy();
    dateOption.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
    await nextTick();

    expect(value()).toBe('date');
    expect(changes.length).toBe(1);

    app.unmount();
  });

  it('control run with NO groupCap: byte-identical-off — all options render, no more-row', async () => {
    const { app, host } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBe(6);
    expect(host.querySelectorAll('.rozie-combobox-more').length).toBe(0);

    app.unmount();
  });
});
