// @vitest-environment happy-dom
/**
 * keep-open.behavior.test.ts — mount-and-drive behavioral proof for the
 * `pinOpen` imperative handle verb (the command-palette-sub-actions
 * prerequisite — a host sub-surface, e.g. an action flyout, moves real DOM
 * focus OUT of the combobox input; the result popup must NOT collapse while
 * pinned).
 *
 * Mirrors seed-query.behavior.test.ts (itself the captcha
 * model-param-shadow.vue.test.ts precedent): mount the REAL committed
 * emitted packages/vue/src/Combobox.vue (transformed by
 * @vitejs/plugin-vue), obtain the `$expose`d handle via a template ref,
 * drive it, and assert on the rendered DOM.
 *
 * Opts into `happy-dom` via the file-level `@vitest-environment` docblock
 * above so the rest of the suite (parse/lowerToIR/compile — no DOM) keeps
 * the fast node-environment default.
 *
 * Asserts:
 *   (a) focus → popup opens (4 options rendered) — baseline sanity.
 *   (b) blur while pinned (pinOpen(true)) → popup STAYS open.
 *   (c) blur while NOT pinned → popup closes (the preserved default).
 *   (d) pinOpen(false) after pinOpen(true) on an already-open popup → the
 *       popup remains open (unpin alone does not close).
 *   (e) render-neutral: never calling pinOpen behaves exactly like the
 *       seedquery baseline (blur closes).
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
];

interface ComboboxHandle {
  focus: () => void;
  clear: () => void;
  seedQuery: (text: unknown) => void;
  pinOpen: (v: unknown) => void;
}

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount Combobox with a template ref to the `$expose` handle, returning the
 * host element and the handle itself.
 */
function mountCombobox() {
  const value = ref<string | null>(null);
  const handleRef = ref<ComboboxHandle | null>(null);
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        ref: handleRef,
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        options: OPTIONS,
        ariaLabel: 'Fruit',
        idBase: 'keep-open-test',
      }),
  });
  app.mount(host);
  return { app, host, handle: () => handleRef.value as ComboboxHandle };
}

describe('Combobox pinOpen — imperative handle verb (behavioral)', () => {
  it('focus opens the popup (baseline sanity)', async () => {
    const { app, host } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBe(4);
    app.unmount();
  });

  it('blur while pinned keeps the popup open', async () => {
    const { app, host, handle } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();
    expect(host.querySelectorAll('[role="option"]').length).toBe(4);

    handle().pinOpen(true);
    input.dispatchEvent(new Event('blur'));
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    expect(input.getAttribute('aria-expanded')).toBe('true');
    app.unmount();
  });

  it('blur while NOT pinned still closes the popup (default preserved)', async () => {
    const { app, host } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();
    expect(host.querySelectorAll('[role="option"]').length).toBe(4);

    input.dispatchEvent(new Event('blur'));
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBe(0);
    app.unmount();
  });

  it('pinOpen(false) alone does not close an already-open popup (unpin != close)', async () => {
    const { app, host, handle } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    handle().pinOpen(true);
    input.dispatchEvent(new Event('focus'));
    await nextTick();
    expect(host.querySelectorAll('[role="option"]').length).toBe(4);

    handle().pinOpen(false);
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    app.unmount();
  });

  it('render-neutral: never calling pinOpen behaves like the seedquery baseline (blur closes)', async () => {
    const { app, host } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();
    expect(host.querySelectorAll('[role="option"]').length).toBe(4);

    input.dispatchEvent(new Event('blur'));
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBe(0);
    app.unmount();
  });
});
