// @vitest-environment happy-dom
/**
 * multiple.behavior.test.ts — mount-and-drive behavioral proof for the `multiple`
 * prop (Phase 86 R1, plan 86-04): the widened sole `value` model, the ported
 * toggle/dedup/fresh-array algorithm, the `selected` field on `change`, the
 * `aria-multiselectable`/`aria-selected` marking, and the flipped
 * `effectiveCloseOnSelect()` default — proven in EACH of the four mutually
 * exclusive render branches (plain / grouped / grouped+capped / windowed), not
 * only the plain one. The SPEC constraint is explicit that a "works except with
 * windowing" caveat is unacceptable.
 *
 * Mirrors group-cap.behavior.test.ts / virtual-flip.behavior.test.ts (itself the
 * seed-query/captcha model-param-shadow.vue.test.ts precedent): mount the REAL
 * committed emitted packages/vue/src/Combobox.vue (transformed by
 * @vitejs/plugin-vue), drive it via real DOM events, and assert on the rendered
 * DOM + the two-way `value` model.
 *
 * RED-FIRST (see the SUMMARY for the captured failing output): the toggle-off
 * and freshness assertions were proven RED against a deliberately-reverted
 * `selectOption()` (no membership check — every pick blindly appended, and the
 * `value` array was mutated in place with `.push`) before being restored to the
 * real port-of-listCore algorithm this file now asserts GREEN against.
 *
 * Asserts, per branch:
 *   (1) toggle: pick then re-pick the SAME option returns `value` to its prior
 *       array (an empty array, in these tests' single-pick setup).
 *   (2) ordering: three distinct picks land in the `value` array in pick order.
 *   (3) dedup: two DIFFERENT options sharing the SAME `value` toggle ONE shared
 *       entry — picking the second never produces `['apple','apple']`.
 *   (4) empty: `[]`, `null`, and `undefined` initial values all render zero
 *       `aria-selected="true"` options and the placeholder stays visible.
 *   (5) freshness: every model write is a NEW array reference (never a mutation
 *       of the prior one) and is never `null` while `multiple` is set.
 *   (6) concurrency: swapping `options` out from under a selection keeps the
 *       selection in the model, keyed by value.
 *   (7) ARIA: the listbox carries `aria-multiselectable="true"` only when
 *       `multiple` is set (ABSENT, not `"false"`, when unset), and a selected
 *       option carries `aria-selected="true"`.
 *   (8) close behavior: the effective `closeOnSelect` default is `false` under
 *       `multiple` (the popup stays open after a pick); an explicit
 *       `:closeOnSelect="true"` still closes it.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = [
  { value: 'apple', label: 'Apple', group: 'fruit' },
  { value: 'banana', label: 'Banana', group: 'fruit' },
  { value: 'cherry', label: 'Cherry', group: 'fruit' },
  { value: 'date', label: 'Date', group: 'fruit' },
  { value: 'carrot', label: 'Carrot', group: 'veg' },
  { value: 'potato', label: 'Potato', group: 'veg' },
];

// A shares the SAME `value` as a SECOND, differently-labeled option — the
// dedup fixture (R1 truth: "duplicate `value`s appearing in `options` resolve
// to a single selection entry"). Both entries sit within groupCap's visible
// window (cap 2) so the dedup test never needs to expand a "+N more" row.
const DUP_OPTIONS = [
  { value: 'apple', label: 'Apple', group: 'fruit' },
  { value: 'apple', label: 'Apple (duplicate value)', group: 'fruit' },
  { value: 'banana', label: 'Banana', group: 'fruit' },
];

const GROUPS = [
  { id: 'fruit', label: 'Fruit' },
  { id: 'veg', label: 'Vegetable' },
];

interface BranchConfig {
  name: string;
  props: Record<string, unknown>;
}

// The four mutually-exclusive render branches this family ships (SPEC: "no
// works-except-with-windowing caveat"). `groups`/`groupCap` are ignored by the
// windowed branch (native grouping is non-virtual-only) — reusing ONE shared
// OPTIONS fixture (each entry tagged with a harmless `group` field) across all
// four is safe. `virtual` itself is NOT set here — see `openBranch()` below:
// the windowed branch starts non-virtual and flips at runtime so its option
// rows are real DOM (TanStack's virtualizer has no real layout to measure
// under happy-dom — see the `openBranch` doc comment for the full mechanism).
const BRANCHES: BranchConfig[] = [
  { name: 'plain', props: {} },
  { name: 'grouped', props: { groups: GROUPS } },
  { name: 'grouped+capped', props: { groups: GROUPS, groupCap: 2 } },
  { name: 'windowed', props: { maxHeight: '200px' } },
];

const hosts: HTMLElement[] = [];
afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount Combobox with `multiple` on by default, a reactive `value` / `options`
 * / `virtual` triple (so a test can swap any of them and re-render), and a
 * `change` event log.
 */
function mountCombobox(
  branchProps: Record<string, unknown>,
  opts: {
    initialValue?: unknown;
    extraProps?: Record<string, unknown>;
    optionsList?: Array<Record<string, unknown>>;
  } = {},
) {
  const { initialValue = null, extraProps = {}, optionsList = OPTIONS } = opts;
  const value = ref<unknown>(initialValue);
  const options = ref<Array<Record<string, unknown>>>(optionsList);
  const virtual = ref<boolean>(!!branchProps.virtual);
  const changes: unknown[] = [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: unknown) => {
          value.value = v;
        },
        onChange: (e: unknown) => changes.push(e),
        options: options.value,
        multiple: true,
        placeholder: 'Pick some…',
        ariaLabel: 'Fruit or vegetable',
        idBase: 'multiple-test',
        ...branchProps,
        virtual: virtual.value,
        ...extraProps,
      }),
  });
  app.mount(host);
  return {
    app,
    host,
    changes,
    value: () => value.value,
    setOptions: (o: Array<Record<string, unknown>>) => {
      options.value = o;
    },
    setVirtual: (v: boolean) => {
      virtual.value = v;
    },
  };
}

interface Mounted {
  host: HTMLElement;
  setVirtual: (v: boolean) => void;
}

/**
 * Open the popup (focus the input) with REAL option rows in the DOM for every
 * branch, including windowed.
 *
 * TanStack's virtualizer has no real layout to measure under happy-dom
 * (`getBoundingClientRect` reports 0), so a combobox mounted with
 * `virtual: true` FROM THE START never settles a non-empty windowed slice —
 * `windowedRows()` (the real TanStack-measured path) stays empty regardless of
 * how long a test waits (confirmed against this exact harness; even
 * `virtual-flip.behavior.test.ts`'s own mount-time-virtual case (f) avoids
 * asserting on option DOM for this reason). Instead this mounts non-virtual,
 * opens (real, unwindowed rows), THEN flips `virtual` true and awaits only a
 * `nextTick()` — landing in the SAME un-windowed fallback frame
 * `virtual-flip.behavior.test.ts`'s test (a) exploits successfully
 * (`windowedView()`'s `$props.virtual && !virtualizer && didMount` branch,
 * live until the rAF-deferred `buildVirtualizer()` actually fires). Since
 * nothing here ever awaits a real macrotask/animation frame, that rAF never
 * fires during the test, so the fallback frame — genuinely rendered through
 * the windowed `<ul r-if="$props.virtual">` markup, exercising every binding
 * task 2 added to it — persists for the whole test.
 */
async function openBranch(branchName: string, mount: Mounted): Promise<HTMLInputElement> {
  const input = mount.host.querySelector('input[role="combobox"]') as HTMLInputElement;
  input.dispatchEvent(new Event('focus'));
  await nextTick();
  if (branchName === 'windowed') {
    mount.setVirtual(true);
    await nextTick();
  }
  return input;
}

function findOptionEl(host: HTMLElement, label: string): HTMLElement | undefined {
  return Array.from(host.querySelectorAll('[role="option"]:not(.rozie-combobox-more)')).find((e) =>
    e.textContent?.includes(label),
  ) as HTMLElement | undefined;
}

/**
 * Click an option by its visible label, expanding a capped group's "+N more"
 * row first if the option isn't directly visible yet (the grouped+capped
 * branch, whenever a test picks past the `groupCap` window).
 */
async function selectByLabel(host: HTMLElement, label: string): Promise<void> {
  let el = findOptionEl(host, label);
  if (!el) {
    const more = host.querySelector('.rozie-combobox-more') as HTMLElement | null;
    if (more) {
      more.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
      await nextTick();
    }
    el = findOptionEl(host, label);
  }
  if (!el) throw new Error(`option not found: ${label}`);
  el.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
  await nextTick();
}

// ── chip-rail helpers (Phase 86 R1, plan 86-05) ─────────────────────────────
function chipEls(host: HTMLElement): HTMLElement[] {
  return Array.from(host.querySelectorAll('.rozie-combobox-chip')) as HTMLElement[];
}
function chipLabels(host: HTMLElement): string[] {
  return chipEls(host).map((el) => el.querySelector('.rozie-combobox-chip__label')?.textContent?.trim() ?? '');
}
function chipRemoveBtn(el: HTMLElement): HTMLButtonElement {
  return el.querySelector('.rozie-combobox-chip__remove') as HTMLButtonElement;
}

for (const branch of BRANCHES) {
  describe(`Combobox multiple — ${branch.name} branch (behavioral)`, () => {
    it('(1) toggle: picking then re-picking the same option returns value to its prior array', async () => {
      const mount = mountCombobox(branch.props);
      const { app, host, value } = mount;
      try {
        await openBranch(branch.name, mount);
        await selectByLabel(host, 'Apple');
        expect(value()).toEqual(['apple']);

        await selectByLabel(host, 'Apple');
        expect(value()).toEqual([]);
      } finally {
        app.unmount();
      }
    });

    it('(2) ordering: three picks land in the value array in pick order', async () => {
      const mount = mountCombobox(branch.props);
      const { app, host, value } = mount;
      try {
        await openBranch(branch.name, mount);
        await selectByLabel(host, 'Cherry');
        await selectByLabel(host, 'Apple');
        await selectByLabel(host, 'Banana');

        expect(value()).toEqual(['cherry', 'apple', 'banana']);
      } finally {
        app.unmount();
      }
    });

    it('(3) dedup: two options sharing a value toggle ONE shared selection entry', async () => {
      const mount = mountCombobox(branch.props, { optionsList: DUP_OPTIONS });
      const { app, host, value } = mount;
      try {
        await openBranch(branch.name, mount);
        await selectByLabel(host, 'Apple (duplicate value)');
        // Only exists AFTER the first pick — but both duplicate rows commit the
        // SAME value, so this single pick already added exactly one entry.
        expect(value()).toEqual(['apple']);

        // Picking the OTHER row sharing the same value toggles it OFF — proof
        // there is one shared selection entry, never `['apple', 'apple']`.
        await selectByLabel(host, 'Apple');
        expect(value()).toEqual([]);
      } finally {
        app.unmount();
      }
    });

    it('(4) empty: [], null, and undefined all render zero selections + the placeholder', async () => {
      for (const initialValue of [[], null, undefined]) {
        const mount = mountCombobox(branch.props, { initialValue });
        const { app, host, value } = mount;
        try {
          const input = await openBranch(branch.name, mount);
          expect(input.getAttribute('placeholder')).toBe('Pick some…');
          expect(input.value).toBe('');
          expect(host.querySelectorAll('[aria-selected="true"]').length).toBe(0);
          // Reading the value back never coerces the empty/nullish start into
          // something else ON THE COMBOBOX'S OWN INITIATIVE (no write happens
          // without a pick). `undefined` is the one exception, and it is Vue's
          // OWN `defineModel('value', { default: null })` doing it, not
          // Combobox's script: Vue auto-emits an `update:value` sync of the
          // declared default the instant an `undefined` prop resolves to it —
          // documented Vue 3.4+ defineModel behavior, framework-level, not a
          // Rozie write.
          const expected = initialValue === undefined ? null : initialValue;
          expect(value()).toEqual(expected);
        } finally {
          app.unmount();
        }
      }
    });

    it('(5) freshness: every write is a fresh array reference, never null', async () => {
      const mount = mountCombobox(branch.props);
      const { app, host, value } = mount;
      try {
        await openBranch(branch.name, mount);
        await selectByLabel(host, 'Apple');
        const afterFirst = value();
        expect(Array.isArray(afterFirst)).toBe(true);
        expect(afterFirst).not.toBeNull();
        expect(afterFirst).toEqual(['apple']);

        await selectByLabel(host, 'Banana');
        const afterSecond = value();
        // IDENTITY, not just deep-equality — the failure this guards is a
        // mutated-in-place array that deep-equals the expected value while
        // React/Solid/Lit/Angular's reference-based change detectors never
        // observe the write.
        expect(afterSecond).not.toBe(afterFirst);
        expect(afterSecond).toEqual(['apple', 'banana']);
        // The PRIOR array is untouched by the second write (no in-place mutation).
        expect(afterFirst).toEqual(['apple']);
        expect(afterSecond).not.toBeNull();
      } finally {
        app.unmount();
      }
    });

    it('(6) concurrency: swapping options out from under a selection keeps it in the model', async () => {
      const mount = mountCombobox(branch.props);
      const { app, host, value, setOptions } = mount;
      try {
        await openBranch(branch.name, mount);
        await selectByLabel(host, 'Apple');
        expect(value()).toEqual(['apple']);

        // Swap to an option set that no longer contains 'apple' at all.
        setOptions([
          { value: 'carrot', label: 'Carrot', group: 'veg' },
          { value: 'potato', label: 'Potato', group: 'veg' },
        ]);
        await nextTick();

        // The model still holds the selection by value — combobox never
        // purges a selection just because `options` changed underneath it.
        expect(value()).toEqual(['apple']);
      } finally {
        app.unmount();
      }
    });

    it('(7) ARIA: aria-multiselectable + per-option aria-selected reflect selection', async () => {
      const mount = mountCombobox(branch.props);
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        const listbox = host.querySelector('[role="listbox"]') as HTMLElement;
        expect(listbox.getAttribute('aria-multiselectable')).toBe('true');

        await selectByLabel(host, 'Apple');
        const appleEl = findOptionEl(host, 'Apple')!;
        expect(appleEl.getAttribute('aria-selected')).toBe('true');
        const bananaEl = findOptionEl(host, 'Banana')!;
        expect(bananaEl.getAttribute('aria-selected')).toBe('false');
      } finally {
        app.unmount();
      }
    });

    it('(7b) ARIA: aria-multiselectable is ABSENT (not "false") when multiple is unset', async () => {
      const mount = mountCombobox(branch.props, { extraProps: { multiple: false } });
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        const listbox = host.querySelector('[role="listbox"]') as HTMLElement;
        expect(listbox.hasAttribute('aria-multiselectable')).toBe(false);
      } finally {
        app.unmount();
      }
    });

    it('(8) close behavior: effective default is false under multiple; explicit true still closes', async () => {
      // Unset closeOnSelect: the effective default flips to `false` under
      // `multiple` — the popup stays open after a pick.
      const stayOpen = mountCombobox(branch.props);
      try {
        const input = await openBranch(branch.name, stayOpen);
        expect(input.getAttribute('aria-expanded')).toBe('true');
        await selectByLabel(stayOpen.host, 'Apple');
        expect(input.getAttribute('aria-expanded')).toBe('true');
      } finally {
        stayOpen.app.unmount();
      }

      // An explicit `:closeOnSelect="true"` still wins under `multiple`.
      const closes = mountCombobox(branch.props, { extraProps: { closeOnSelect: true } });
      try {
        const input = await openBranch(branch.name, closes);
        expect(input.getAttribute('aria-expanded')).toBe('true');
        await selectByLabel(closes.host, 'Apple');
        expect(input.getAttribute('aria-expanded')).toBe('false');
      } finally {
        closes.app.unmount();
      }
    });

    it('(9) chips: render inside the control before the input, in selection order, deduplicated', async () => {
      const mount = mountCombobox(branch.props, { initialValue: ['banana', 'apple', 'banana'] });
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        expect(chipLabels(host)).toEqual(['Banana', 'Apple']);
        const chipsList = host.querySelector('.rozie-combobox-chips') as HTMLElement;
        const input = host.querySelector('input[role="combobox"]') as HTMLElement;
        expect(chipsList).not.toBeNull();
        // The chips list precedes the input in document order (D-13: before
        // the input, inside the same #anchor slot fill).
        // eslint-disable-next-line no-bitwise
        expect(!!(chipsList.compareDocumentPosition(input) & Node.DOCUMENT_POSITION_FOLLOWING)).toBe(true);
      } finally {
        app.unmount();
      }
    });

    it('(10) chips: a value whose option has disappeared from options persists, labelled by its raw value', async () => {
      const mount = mountCombobox(branch.props, { initialValue: ['apple', 'ghost-value'] });
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        expect(chipLabels(host)).toEqual(['Apple', 'ghost-value']);
      } finally {
        app.unmount();
      }
    });

    it('(11) chips: activating a remove control removes exactly that value and emits the same payload shape a toggle-off emits', async () => {
      const mount = mountCombobox(branch.props, { initialValue: ['apple', 'banana'] });
      const { app, host, value, changes } = mount;
      try {
        await openBranch(branch.name, mount);
        const target = chipEls(host).find((el) => el.textContent?.includes('Apple'))!;
        chipRemoveBtn(target).dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true }));
        await nextTick();
        expect(value()).toEqual(['banana']);
        const last = changes[changes.length - 1] as { value: unknown; option: { value: string } | null; selected: boolean };
        expect(last.value).toEqual(['banana']);
        expect(last.selected).toBe(false);
        expect(last.option?.value).toBe('apple');
      } finally {
        app.unmount();
      }
    });

    it('(12) chips: every remove control is focusable and carries an aria-label naming what it removes', async () => {
      const mount = mountCombobox(branch.props, { initialValue: ['apple'] });
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        const btn = chipRemoveBtn(chipEls(host)[0]);
        expect(btn.tagName).toBe('BUTTON');
        expect(btn.getAttribute('type')).toBe('button');
        expect(btn.hasAttribute('disabled')).toBe(false);
        expect(btn.getAttribute('aria-label')).toMatch(/Apple/);
      } finally {
        app.unmount();
      }
    });

    it('(13) chips: Backspace on an empty query removes the last chip; Backspace with a non-empty query does not', async () => {
      const mount = mountCombobox(branch.props, { initialValue: ['apple', 'banana'] });
      const { app, host, value } = mount;
      try {
        const input = await openBranch(branch.name, mount);

        // Non-empty query: Backspace must NOT remove a chip.
        input.value = 'ba';
        input.dispatchEvent(new Event('input'));
        await nextTick();
        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'Backspace', bubbles: true, cancelable: true }));
        await nextTick();
        expect(value()).toEqual(['apple', 'banana']);

        // Empty query: Backspace removes the LAST chip.
        input.value = '';
        input.dispatchEvent(new Event('input'));
        await nextTick();
        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'Backspace', bubbles: true, cancelable: true }));
        await nextTick();
        expect(value()).toEqual(['apple']);
      } finally {
        app.unmount();
      }
    });

    it('(14) chips: no chip rail renders when multiple is unset, and the control markup is unchanged', async () => {
      const mount = mountCombobox(branch.props, { extraProps: { multiple: false }, initialValue: null });
      const { app, host } = mount;
      try {
        await openBranch(branch.name, mount);
        expect(host.querySelector('.rozie-combobox-chips')).toBeNull();
        expect(chipEls(host).length).toBe(0);
      } finally {
        app.unmount();
      }
    });
  });
}
