// @vitest-environment happy-dom
/**
 * resolvers.behavior.test.ts — mount-and-drive behavioral proof for the E2
 * audit finding (quick task 260903-0s1): `syncQueryToValue()` bypassed the
 * `optionValue`/`optionLabel`/`optionDisabled` resolvers, reading raw
 * `.value`/`.label` properties directly — silently breaking the documented
 * resolver props and primitive-string options on BOTH the mount path
 * ($onMount → syncQueryToValue()) and the external-value path
 * ($watch(() => $props.value, ...) → syncQueryToValue()).
 *
 * Mirrors seed-query.behavior.test.ts / multiple.behavior.test.ts: mount the
 * REAL committed emitted packages/vue/src/Combobox.vue leaf (transformed by
 * @vitejs/plugin-vue), drive it via real DOM/reactive-prop changes, and
 * assert on the rendered `<input>` text.
 *
 * Asserts:
 *   R1 (RED before the fix): `{ id, name }`-shaped options + optionValue/
 *       optionLabel resolvers + a pre-set `value` — the input shows the
 *       RESOLVED label on mount, not empty.
 *   R2 (RED before the fix): primitive string options + a pre-set `value` —
 *       the input shows that string on mount.
 *   R3 (RED before the fix): the EXTERNAL-WRITE path — writing a DIFFERENT
 *       value into the model from the parent re-resolves the input text to
 *       the newly-selected label.
 *   R4 (regression guard, green both sides): plain `{ value, label }` options
 *       with a pre-set value still render the label — today's only working
 *       case must keep working.
 *   R5 (new coverage, green both sides): an `optionDisabled` resolver marks a
 *       row disabled — `aria-disabled="true"` on the rendered option, and
 *       ArrowDown navigation skips it (closes the third zero-coverage
 *       resolver the audit names — `filteredOptions()`/`nextEnabled()`
 *       already route through `disabledOf()` correctly; this is coverage,
 *       not a fix).
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const hosts: HTMLElement[] = [];
afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

interface MountOpts {
  options: Array<Record<string, unknown>> | string[];
  initialValue: unknown;
  extraProps?: Record<string, unknown>;
}

function mountCombobox(opts: MountOpts) {
  const value = ref<unknown>(opts.initialValue);
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: unknown) => {
          value.value = v;
        },
        options: opts.options,
        ariaLabel: 'Fruit',
        idBase: 'resolvers-test',
        ...opts.extraProps,
      }),
  });
  app.mount(host);
  return {
    app,
    host,
    setValue: (v: unknown) => {
      value.value = v;
    },
  };
}

function getInput(host: HTMLElement): HTMLInputElement {
  return host.querySelector('input[role="combobox"]') as HTMLInputElement;
}

describe('Combobox syncQueryToValue — option resolver routing (behavioral, E2)', () => {
  it('R1: optionValue/optionLabel resolvers resolve the label for a pre-set value on mount', async () => {
    const options = [
      { id: 'a', name: 'Apple' },
      { id: 'b', name: 'Banana' },
    ];
    const { app, host } = mountCombobox({
      options,
      initialValue: 'a',
      extraProps: {
        optionValue: (o: { id: string }) => o.id,
        optionLabel: (o: { name: string }) => o.name,
      },
    });
    try {
      await nextTick();
      expect(getInput(host).value).toBe('Apple');
    } finally {
      app.unmount();
    }
  });

  it('R2: primitive string options render the pre-set value on mount', async () => {
    const { app, host } = mountCombobox({
      options: ['Apple', 'Banana', 'Cherry'],
      initialValue: 'Banana',
    });
    try {
      await nextTick();
      expect(getInput(host).value).toBe('Banana');
    } finally {
      app.unmount();
    }
  });

  it('R3: an external value write re-resolves the input to the newly-selected label', async () => {
    const options = [
      { id: 'a', name: 'Apple' },
      { id: 'b', name: 'Banana' },
    ];
    const { app, host, setValue } = mountCombobox({
      options,
      initialValue: 'a',
      extraProps: {
        optionValue: (o: { id: string }) => o.id,
        optionLabel: (o: { name: string }) => o.name,
      },
    });
    try {
      await nextTick();
      expect(getInput(host).value).toBe('Apple');

      setValue('b');
      await nextTick();
      expect(getInput(host).value).toBe('Banana');
    } finally {
      app.unmount();
    }
  });

  it('R4 (regression guard): plain {value,label} options with a pre-set value still render the label', async () => {
    const options = [
      { value: 'apple', label: 'Apple' },
      { value: 'banana', label: 'Banana' },
    ];
    const { app, host } = mountCombobox({ options, initialValue: 'banana' });
    try {
      await nextTick();
      expect(getInput(host).value).toBe('Banana');
    } finally {
      app.unmount();
    }
  });

  it('R5 (new coverage): optionDisabled marks a row aria-disabled and keyboard navigation skips it', async () => {
    const options = [
      { id: 'a', name: 'Apple' },
      { id: 'b', name: 'Banana' },
      { id: 'c', name: 'Cherry' },
    ];
    const { app, host } = mountCombobox({
      options,
      initialValue: null,
      extraProps: {
        optionValue: (o: { id: string }) => o.id,
        optionLabel: (o: { name: string }) => o.name,
        optionDisabled: (o: { id: string }) => o.id === 'b',
      },
    });
    try {
      const input = getInput(host);
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      const optionEls = Array.from(host.querySelectorAll('[role="option"]')) as HTMLElement[];
      expect(optionEls.length).toBe(3);
      const bananaEl = optionEls.find((el) => el.textContent?.includes('Banana'))!;
      expect(bananaEl.getAttribute('aria-disabled')).toBe('true');

      // ArrowDown from the top skips the disabled 'Banana' row and lands on
      // 'Cherry' (nextEnabled() already routes through disabledOf() — this is
      // NEW coverage of existing correct behavior, not a fix).
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
      await nextTick();
      input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
      await nextTick();

      const activeEl = host.querySelector('[aria-selected], .rozie-combobox-option--active') as HTMLElement | null;
      const activeDescId = input.getAttribute('aria-activedescendant');
      const activeById = activeDescId ? host.querySelector(`#${CSS.escape(activeDescId)}`) : null;
      expect((activeById ?? activeEl)?.textContent).toContain('Cherry');
    } finally {
      app.unmount();
    }
  });
});
