// @vitest-environment happy-dom
/**
 * scroll-active.behavior.test.ts — mount-and-drive behavioral proof that
 * `scrollActiveIntoView()` also scrolls the ACTIVE option into view for a
 * NON-virtual (non-windowed) popup, not just the `virtual` windowed path.
 *
 * Mirrors keep-open.behavior.test.ts (itself the seed-query/group-cap
 * precedent): mount the REAL committed emitted packages/vue/src/Combobox.vue
 * (transformed by @vitejs/plugin-vue), drive it via real DOM events, and
 * assert on the rendered DOM.
 *
 * happy-dom implements NO real layout (no scrollHeight/clientHeight, so a
 * real scroll assertion is meaningless there) — so this test asserts the
 * MECHANISM instead of pixels: monkey-patch `Element.prototype.scrollIntoView`
 * (happy-dom implements it as a no-op fn) and assert it is CALLED with
 * `{ block: 'nearest' }` on the ACTIVE option element (by `el.id`) after
 * ArrowDown moves the active index in a non-virtual list of ~20 options.
 *
 * Asserts:
 *   (a) ArrowDown (popup open) calls scrollIntoView({ block: 'nearest' }) on
 *       the new active option element.
 *   (b) repeated ArrowDown keeps calling it on the newly-active option.
 *   (c) scrollIntoView is NOT called while the popup is closed (no calls
 *       accrue before focus/open).
 */
import { describe, it, expect, afterEach, vi } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = Array.from({ length: 20 }, (_, i) => ({
  value: `opt-${i}`,
  label: `Option ${i}`,
}));

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Spies on `Element.prototype.scrollIntoView`, recording `{ el, opts }` per
 * call (captured via a plain `function` so `this` resolves to the element —
 * `spy.mock.calls[n]` only carries the call ARGUMENTS, not the receiver).
 * Always restore via `spy.mockRestore()` in a `finally` so a mid-test
 * assertion failure can never leak a live spy into the next test.
 */
function spyOnScrollIntoView() {
  const calls: { el: Element; opts: unknown }[] = [];
  const spy = vi
    .spyOn(Element.prototype, 'scrollIntoView')
    .mockImplementation(function (this: Element, opts?: unknown) {
      calls.push({ el: this, opts });
    });
  return { spy, calls };
}

/**
 * Mount Combobox (non-virtual — the `virtual` prop is left at its `false`
 * default), returning the host element.
 */
function mountCombobox() {
  const value = ref<string | null>(null);
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        options: OPTIONS,
        ariaLabel: 'Options',
        idBase: 'scroll-active-test',
      }),
  });
  app.mount(host);
  return { app, host };
}

describe('Combobox scrollActiveIntoView — non-virtual list keeps active option in view (behavioral)', () => {
  it('ArrowDown scrolls the newly-active option into view', async () => {
    const { spy, calls } = spyOnScrollIntoView();
    try {
      const { app, host } = mountCombobox();
      try {
        const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
        input.dispatchEvent(new Event('focus'));
        await nextTick();
        expect(host.querySelectorAll('[role="option"]').length).toBe(20);
        // Nothing should have scrolled yet — focus alone doesn't move activeIndex.
        expect(calls.length).toBe(0);

        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
        await nextTick();

        expect(calls.length).toBe(1);
        expect(calls[0]!.opts).toEqual({ block: 'nearest' });
        expect((calls[0]!.el as HTMLElement).id).toBe('scroll-active-test-opt-0');
        expect((calls[0]!.el as HTMLElement).getAttribute('role')).toBe('option');

        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
        await nextTick();

        expect(calls.length).toBe(2);
        expect((calls[1]!.el as HTMLElement).id).toBe('scroll-active-test-opt-1');
      } finally {
        app.unmount();
      }
    } finally {
      spy.mockRestore();
    }
  });

  it('does not call scrollIntoView while the popup is closed', async () => {
    const { spy, calls } = spyOnScrollIntoView();
    try {
      const { app, host } = mountCombobox();
      try {
        const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;

        // ArrowDown before the popup has ever opened only opens it + sets
        // activeIndex 0 (the `!wasOpen` branch, an early return BEFORE
        // scrollActiveIntoView() is reached) — it should not scroll.
        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
        await nextTick();
        expect(calls.length).toBe(0);

        // Now open + move to a non-zero activeIndex.
        input.dispatchEvent(new Event('focus'));
        await nextTick();
        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true }));
        await nextTick();
        expect(calls.length).toBe(1);

        // Escape falls through to the unconditional scrollActiveIntoView() call
        // at the end of onKeydown with activeIndex still >= 0 but isOpen now
        // false — this is the guard scrollActiveIntoView() itself must apply.
        calls.length = 0;
        input.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }));
        await nextTick();
        expect(host.querySelectorAll('[role="option"]').length).toBe(0);
        expect(calls.length).toBe(0);
      } finally {
        app.unmount();
      }
    } finally {
      spy.mockRestore();
    }
  });
});
