// @vitest-environment happy-dom
/**
 * seed-query.behavior.test.ts — mount-and-drive behavioral proof for the
 * `seedQuery` imperative handle verb (a small, additive prerequisite for
 * command-palette #2 levels/restore-on-pop — repopulating the combobox's
 * input text on back-navigation).
 *
 * Mirrors captcha's tests/model-param-shadow.vue.test.ts precedent: mount the
 * REAL committed emitted packages/vue/src/Combobox.vue (transformed by
 * @vitejs/plugin-vue), obtain the `$expose`d handle via a template ref, drive
 * it, and assert on the rendered DOM — the only way to catch a
 * runtime-semantic regression (typechecks clean, wrong behavior) rather than
 * a text/AST assertion.
 *
 * Opts into `happy-dom` via the file-level `@vitest-environment` docblock
 * above so the rest of the suite (parse/lowerToIR/compile — no DOM) keeps the
 * fast node-environment default.
 *
 * Asserts the two documented seedQuery guarantees:
 *   1. It sets the rendered `<input>`'s value to the seeded text.
 *   2. It re-filters the option list (filteredOptions() reads $data.query),
 *      narrowing to the matching option(s).
 * And the two documented NON-effects (imperative-only, not a second model):
 *   3. It does NOT touch the `value` model / fire `change`.
 *   4. It does NOT open the popup on its own (matches focus()/typing, which
 *      DO open it — seedQuery is a pure text-seed, not a user interaction).
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from the fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this
// SFC into a mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

const OPTIONS = [
  { value: 'apple', label: 'Apple' },
  { value: 'banana', label: 'Banana' },
  { value: 'cherry', label: 'Cherry' },
  { value: 'date', label: 'Date' },
];

interface ComboboxHandle {
  focus: () => void;
  clear: () => void;
  seedQuery: (text: unknown) => void;
}

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount Combobox with a template ref to the `$expose` handle, returning the
 * host element, the live `value` ref (two-way `value` model), the collected
 * `change` events, and the handle itself.
 */
function mountCombobox() {
  const value = ref<string | null>(null);
  const changes: Array<Record<string, unknown>> = [];
  const handleRef = ref<ComboboxHandle | null>(null);
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        ref: handleRef,
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        options: OPTIONS,
        ariaLabel: 'Fruit',
        idBase: 'seed-query-test',
        onChange: (e: Record<string, unknown>) => changes.push(e),
      }),
  });
  app.mount(host);
  return { app, value, changes, host, handle: () => handleRef.value as ComboboxHandle };
}

describe('Combobox seedQuery — imperative handle verb (behavioral)', () => {
  it('sets the rendered input value to the seeded text', async () => {
    const { app, host, handle } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    expect(input.value).toBe('');

    handle().seedQuery('cher');
    await nextTick();

    expect(input.value).toBe('cher');
    app.unmount();
  });

  it('re-filters the option list to matches (filteredOptions() reads $data.query)', async () => {
    const { app, host, handle } = mountCombobox();

    // Open the popup so the (now-filtered) option list renders.
    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    input.dispatchEvent(new Event('focus'));
    await nextTick();
    expect(host.querySelectorAll('[role="option"]').length).toBe(4);

    handle().seedQuery('cher');
    await nextTick();

    const options = host.querySelectorAll('[role="option"]');
    expect(options.length).toBe(1);
    expect(options[0].textContent).toContain('Cherry');
    app.unmount();
  });

  it('coerces null/undefined to an empty string (never throws, never renders "null")', async () => {
    const { app, host, handle } = mountCombobox();

    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    handle().seedQuery('cher');
    await nextTick();
    expect(input.value).toBe('cher');

    handle().seedQuery(null);
    await nextTick();
    expect(input.value).toBe('');

    handle().seedQuery(undefined);
    await nextTick();
    expect(input.value).toBe('');
    app.unmount();
  });

  it('does NOT touch the value model or fire change (imperative-only, not a selection)', async () => {
    const { app, value, changes, handle } = mountCombobox();

    handle().seedQuery('cher');
    await nextTick();

    expect(value.value).toBe(null);
    expect(changes).toEqual([]);
    app.unmount();
  });

  it('does NOT open the popup on its own (a pure text-seed, unlike focus()/typing)', async () => {
    const { app, host, handle } = mountCombobox();

    handle().seedQuery('cher');
    await nextTick();

    expect(host.querySelectorAll('[role="option"]').length).toBe(0);
    app.unmount();
  });
});
