// @vitest-environment happy-dom
/**
 * virtual-flip.behavior.test.ts — RED-first mount-and-drive behavioral proof that
 * `@rozie-ui/combobox`'s `virtual` prop is LIVE-FLIPPABLE (combobox-virtual-reactivity
 * phase — VIRT-BUILD / VIRT-TEARDOWN / VIRT-WATCH / VIRT-FALLBACK).
 *
 * Today the TanStack virtualizer is constructed exactly once in `$onMount` under
 * `if ($props.virtual)`, with NO `$watch`. A runtime `false→true` flip therefore
 * renders a BLANK popup (`windowedRows()` returns `[]` while `virtual && virtualizer
 * === null` — windowing.rzts ~L95-105) and a `true→false` flip leaves a live
 * ResizeObserver + stale windowing state (only `$onUnmount` ever calls
 * `virtualizerCleanup`). After the source fix (buildVirtualizer/teardownVirtualizer +
 * a lazy `$watch(() => $props.virtual)` + the combobox-side `windowedView()` fallback),
 * flipping `virtual` at any time builds/tears the windowing engine correctly and the
 * mid-flip frame renders the un-windowed full slice instead of a blank list.
 *
 * Mirrors scroll-active.behavior.test.ts / keep-open.behavior.test.ts: mount the REAL
 * committed emitted packages/vue/src/Combobox.vue (transformed by @vitejs/plugin-vue),
 * drive it via real DOM events + a reactive `virtual` ref (mirroring the scroll-active
 * `value` ref + `onUpdate:value` pattern), and assert on the rendered DOM.
 *
 * happy-dom implements NO real layout, and Vue's `nextTick()` microtask resolves
 * BEFORE the rAF macrotask the fix's `buildVirtualizer()` re-invocation is deferred
 * behind — so every "flip then assert" step below asserts the state RIGHT AFTER
 * `await nextTick()`, i.e. the deterministic mid-flip frame where the virtualizer is
 * still null and the combobox-side `windowedView()` fallback (not `windowedRows()`)
 * must be what renders.
 *
 * Asserts:
 *   (a) mount NON-virtual (200 options) → focus/open (flat count === 200) → flip
 *       `virtual` true → after nextTick the popup is NOT blank (count > 0 via the
 *       un-windowed fallback). RED on the current leaf: no $watch → the windowed
 *       branch mounts with virtualizer===null → windowedRows() → [] → count 0.
 *   (b) flip virtual true→false → the flat/grouped render is restored, and a
 *       `groups` prop set produces `role="group"` blocks (expandedGroups behavior is
 *       exercised via a dedicated grouped mount).
 *   (c) rapid double-flip (false→true→false→true) settles to a non-blank virtual
 *       popup (count > 0) — idempotence.
 *   (d) flip while CLOSED then open → the popup paints (count > 0 after focus).
 *   (e) virtual:false never-flipped → flat list renders and blur closes (count 0
 *       after blur) — the off-path behavioral byte-identity proxy.
 *   (f) mount virtual:TRUE (constructs the virtualizer + observer in $onMount), spy
 *       ResizeObserver.prototype.disconnect, flip true→false → disconnect is called
 *       (teardown ran). RED on the current leaf: no $watch → disconnect NOT called
 *       (the observer leaks).
 */
import { describe, it, expect, afterEach, vi } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs` from the
// fixed Combobox.rozie source) — @vitejs/plugin-vue transforms this SFC into a
// mountable component.
import Combobox from '../packages/vue/src/Combobox.vue';

// happy-dom@15 ships a ResizeObserver implementation, but guard defensively (test
// scaffold only, NEVER source) in case a future happy-dom major drops it — a minimal
// observe/unobserve/disconnect shim keeps assertion (f) meaningful either way.
if (typeof (globalThis as { ResizeObserver?: unknown }).ResizeObserver === 'undefined') {
  (globalThis as unknown as { ResizeObserver: unknown }).ResizeObserver = class {
    observe() {}
    unobserve() {}
    disconnect() {}
  };
}

const OPTIONS = Array.from({ length: 200 }, (_, i) => ({
  value: `opt-${i}`,
  label: `Option ${i}`,
}));

const GROUPS = [
  { id: 'g1', label: 'Group 1' },
  { id: 'g2', label: 'Group 2' },
];
const GROUPED_OPTIONS = OPTIONS.map((o, i) => ({
  ...o,
  group: i % 2 === 0 ? 'g1' : 'g2',
}));

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

interface MountOpts {
  virtual?: boolean;
  grouped?: boolean;
}

/**
 * Mount Combobox with a reactive `virtual` ref (so a test can flip it and re-render,
 * mirroring the scroll-active `value` ref + `onUpdate:value` pattern).
 */
function mountCombobox(opts: MountOpts = {}) {
  const value = ref<string | null>(null);
  const virtual = ref<boolean>(!!opts.virtual);
  const options = opts.grouped ? GROUPED_OPTIONS : OPTIONS;
  const groupsArg = opts.grouped ? GROUPS : [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(Combobox, {
        value: value.value,
        'onUpdate:value': (v: string | null) => {
          value.value = v;
        },
        options,
        groups: groupsArg,
        ariaLabel: 'Options',
        idBase: 'virtual-flip-test',
        virtual: virtual.value,
        maxHeight: '200px',
      }),
  });
  app.mount(host);
  return { app, host, virtual };
}

describe('Combobox virtual prop — live-flippable windowing (behavioral)', () => {
  it('(a) false→true flip renders a non-blank popup (mid-flip fallback frame)', async () => {
    const { app, host, virtual } = mountCombobox({ virtual: false });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      expect(host.querySelectorAll('[role="option"]').length).toBe(200);

      virtual.value = true;
      await nextTick();

      expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    } finally {
      app.unmount();
    }
  });

  it('(b) true→false flip restores the flat/grouped render + resets expandedGroups', async () => {
    const { app, host, virtual } = mountCombobox({ virtual: true, grouped: true });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      virtual.value = false;
      await nextTick();

      // Grouped render is active (isGrouped() is pure-derived from `groups`/`virtual`).
      expect(host.querySelectorAll('[role="group"]').length).toBeGreaterThan(0);
      expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    } finally {
      app.unmount();
    }
  });

  it('(c) rapid double-flip (false→true→false→true) settles non-blank', async () => {
    const { app, host, virtual } = mountCombobox({ virtual: false });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      virtual.value = true;
      await nextTick();
      virtual.value = false;
      await nextTick();
      virtual.value = true;
      await nextTick();

      expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    } finally {
      app.unmount();
    }
  });

  it('(d) flip while CLOSED then open paints the popup', async () => {
    const { app, host, virtual } = mountCombobox({ virtual: false });
    try {
      // No focus dispatched yet — the popup is closed.
      virtual.value = true;
      await nextTick();

      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();

      expect(host.querySelectorAll('[role="option"]').length).toBeGreaterThan(0);
    } finally {
      app.unmount();
    }
  });

  it('(e) virtual:false never-flipped is byte-identical to today (blur closes)', async () => {
    const { app, host } = mountCombobox({ virtual: false });
    try {
      const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
      input.dispatchEvent(new Event('focus'));
      await nextTick();
      expect(host.querySelectorAll('[role="option"]').length).toBe(200);

      input.dispatchEvent(new Event('blur'));
      await nextTick();

      expect(host.querySelectorAll('[role="option"]').length).toBe(0);
    } finally {
      app.unmount();
    }
  });

  it('(f) true→false flip disconnects the ResizeObserver (no leak)', async () => {
    const disconnectSpy = vi.spyOn(ResizeObserver.prototype, 'disconnect');
    try {
      const { app, host, virtual } = mountCombobox({ virtual: true });
      try {
        const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
        input.dispatchEvent(new Event('focus'));
        await nextTick();

        // Let the mount-time rAF-deferred kickWindow() settle first: it is what calls
        // virtualizer._willUpdate(), which attaches the scroll-rect/measurement
        // ResizeObserver(s) to the real scroll element. A real macrotask wait (NOT just
        // nextTick's microtask) is required here — this is the observer we assert gets
        // disconnected below, so it must actually exist first.
        await new Promise((resolve) => setTimeout(resolve, 50));
        await nextTick();

        expect(disconnectSpy).not.toHaveBeenCalled();

        virtual.value = false;
        await nextTick();

        expect(disconnectSpy).toHaveBeenCalled();
      } finally {
        app.unmount();
      }
    } finally {
      disconnectSpy.mockRestore();
    }
  });
});
