import { test, expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// tests/visual-regression/package.json sets "type": "module", so __dirname is
// not defined here. Synthesize it from import.meta.url.
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * FULL-PAGE (viewport) screenshot cells for the pure-Rozie overlay families that
 * render OUTSIDE the chrome-reset `[data-testid="rozie-mount"]` wrapper.
 *
 * WHY A SEPARATE SPEC (not matrix.spec.ts): the standard matrix clips every
 * screenshot to `getByTestId('rozie-mount')`. Two of the four new @rozie-ui
 * families escape that clip by design:
 *
 *   - DialogScreenshot renders via the native `<dialog>` + `showModal()`, which
 *     paints the modal box AND its `::backdrop` in the browser TOP LAYER —
 *     deliberately escaping z-index / overflow / transform ancestors (the whole
 *     point of `<dialog>`). A mount-clipped capture would miss the top-layer box
 *     and the backdrop scrim entirely.
 *   - ToasterScreenshot renders its region `position: fixed` in a viewport corner
 *     (top-right), so the toast is laid out relative to the viewport, NOT the
 *     mount wrapper — again outside the clip.
 *
 * Both are therefore captured PAGE-LEVEL (`expect(page).toHaveScreenshot(...)`),
 * so the viewport raster includes the top-layer dialog / fixed-corner toast.
 *
 * Reference topology (D-10): per-example baseline keyed by example only — all 6
 * targets diff against the SAME `${name}.png` (the config's
 * `snapshotPathTemplate: '__screenshots__/{arg}{ext}'` omits the target suffix).
 * A target that "renders wrong but consistently" still gets caught.
 *
 * BASELINES ARE LINUX-DOCKER-GENERATED (feedback_vr_linux_baselines): no
 * macOS-rendered PNG is committed here. Until the Linux baseline for an example
 * lands, the cell auto-fixmes via `baselineExists()` (green-skipped, never red) —
 * mirroring the matrix.spec.ts baseline-availability gate. The per-target built
 * check additionally fixmes a cell whose `dist/<target>/` sub-build is absent
 * (e.g. the Angular soft-fail column).
 */

const TARGETS = ['vue', 'react', 'svelte', 'angular', 'solid', 'lit'] as const;
const EXAMPLES = [
  'DialogScreenshot',
  'ToasterScreenshot',
  // TOAST-STACK (toast-ux-cluster) — the opt-in `stacked` collapsed-mode
  // pixel cell. Same `position:fixed` top-right corner as ToasterScreenshot,
  // so it escapes the matrix mount clip too; a SEPARATE baseline (4 sticky
  // toasts, collapsed depth-driven grid overlay, depth>=3 hidden).
  'ToasterStackedScreenshot',
  // @rozie-ui/popover — the floating panel is `position: absolute` (laid out by
  // Floating UI relative to the anchor, not the rozie-mount wrapper), so it
  // escapes the matrix mount clip and is captured PAGE-LEVEL here. The demo seeds
  // open=true so the panel + arrow paint on mount; Floating UI computes identical
  // x/y from the same anchor/viewport across all six targets (the engine-computed
  // byte-identity premise), so a single shared baseline holds.
  'PopoverScreenshot',
  // @rozie-ui/command-palette — the cmdk-style menu renders its overlay
  // `position: fixed` full-viewport (a scrim + a centered role="dialog" panel),
  // r-if="open" gated. The demo seeds open=true + a fixed :items list (query empty),
  // so the centered panel + the full command list paint on mount. The fixed overlay
  // is laid out relative to the VIEWPORT (not the rozie-mount wrapper), so it escapes
  // the matrix mount clip and is captured PAGE-LEVEL here (the Dialog precedent). The
  // component focuses the search input on open, so the capture HIDES the text caret
  // (`caret: 'hide'`) to keep it deterministic. Per D-10 all 6 targets diff against
  // the same shared CommandPaletteScreenshot.png.
  'CommandPaletteScreenshot',
] as const;

// Baseline-availability gate (per-example), copied from matrix.spec.ts. When
// __screenshots__/<Name>.png is missing the cells for that example downgrade to
// test.fixme so the suite stays green until a Linux-Docker baseline regen lands
// the PNG.
//
// Bootstrap escape hatch (matrix.spec.ts parity): a brand-new example has a
// chicken-and-egg problem — its cell is test.fixme until its .png exists, but the
// .png can only be generated by running the cell with Playwright's `-u` (which does
// NOT override test.fixme). Set ROZIE_VR_BOOTSTRAP_BASELINE=<ExampleName>
// (comma-separated) to force-ungate for ONE `-u` pass. Used only by the Docker
// baseline-regen recipe; never set in CI.
const BOOTSTRAP_BASELINES = new Set(
  (process.env.ROZIE_VR_BOOTSTRAP_BASELINE ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
);
function baselineExists(name: string): boolean {
  if (BOOTSTRAP_BASELINES.has(name)) return true;
  return existsSync(resolve(__dirname, `../__screenshots__/${name}.png`));
}

for (const example of EXAMPLES) {
  const hasBaseline = baselineExists(example);
  for (const target of TARGETS) {
    const built = existsSync(
      resolve(__dirname, `../dist/${target}/host/entry.${target}.html`),
    );
    // Cell fixme-gates on EITHER the per-target build availability (the Angular
    // soft-fail column, or any uncompiled target) OR the per-example baseline PNG
    // presence (until the Linux-Docker regen lands).
    const runner = !built || !hasBaseline ? test.fixme : test;
    runner(`${example} · ${target}`, async ({ page }) => {
      await page.goto(`/?example=${example}&target=${target}`);

      if (example === 'DialogScreenshot') {
        // The body testid pierces Lit's shadow root AND the top layer — its
        // visibility proves the native <dialog> showModal()'d on mount and the
        // top-layer box + ::backdrop have painted before the clip.
        await expect(page.getByTestId('screenshot-dialog-body')).toBeVisible({
          timeout: 15_000,
        });
      } else if (example === 'ToasterScreenshot') {
        // The demo's $onMount enqueues exactly one sticky (:duration="0") toast via
        // the $refs.toaster.show() handle; each toast carries role="status". Wait
        // for the single fixed-corner toast before the clip. role= pierces Lit's shadow.
        await expect(page.locator('[role="status"]')).toHaveCount(1, {
          timeout: 15_000,
        });
      } else if (example === 'ToasterStackedScreenshot') {
        // The demo's $onMount enqueues FOUR sticky toasts + `stacked`; the pointer
        // never hovers, so the collapsed depth-driven grid overlay paints (newest
        // on top, depth>=3 hidden — the 4th toast fades to opacity 0 but stays in
        // the DOM). Wait for all 4 role="status" entries before the clip (the
        // COUNT proves the queue settled even though one is visually hidden).
        await expect(page.locator('[role="status"]')).toHaveCount(4, {
          timeout: 15_000,
        });
      } else if (example === 'PopoverScreenshot') {
        // The demo seeds open=true; the floating panel is r-if="open"
        // (`.rozie-popover-floating`). Its visibility proves the panel mounted AND
        // Floating UI applied left/top before the clip. The class locator pierces
        // Lit's open shadow and is role-INDEPENDENT: a default click popover is now
        // non-modal + role-neutral (no role="dialog" unless `modal` is set).
        await expect(page.locator('.rozie-popover-floating')).toBeVisible({
          timeout: 15_000,
        });
      } else if (example === 'CommandPaletteScreenshot') {
        // The demo seeds open=true; the overlay is r-if="open" with a centered
        // role="dialog" panel over a role="listbox". Wait for the panel AND all 6
        // seeded command options (unfiltered list, empty query) before the clip.
        // role="option" matches exactly the 6 <li> rows (a `[class*=...]` substring
        // locator over-matches: each option's `-label`/`-group` child class AND the
        // `--active` modifier also contain the substring → 18 hits). role= pierces
        // Lit's shadow and is unaffected by React CSS-Modules class hashing.
        await expect(page.locator('[role="dialog"]')).toBeVisible({
          timeout: 15_000,
        });
        await expect(page.getByRole('option')).toHaveCount(6, { timeout: 15_000 });
        // REGRESSION GUARD (snapshot-cements-bugs): the results list must render
        // IN FLOW inside the panel, not as an absolute popup culled by the panel's
        // overflow:hidden. toHaveCount above (DOM presence) and Playwright's
        // CSS-visibility BOTH passed while the list hung clipped below a collapsed
        // 36px panel — only a GEOMETRIC containment check catches that. Assert the
        // first option's box sits within the dialog panel's box.
        const dialogBox = await page.locator('[role="dialog"]').boundingBox();
        const optionBox = await page.getByRole('option').first().boundingBox();
        expect(dialogBox).not.toBeNull();
        expect(optionBox).not.toBeNull();
        expect(optionBox!.y).toBeGreaterThanOrEqual(dialogBox!.y - 1);
        expect(optionBox!.y + optionBox!.height).toBeLessThanOrEqual(
          dialogBox!.y + dialogBox!.height + 1,
        );
      }

      // PAGE-level (viewport) capture so the top-layer dialog / fixed-corner toast
      // are included — a mount-clipped capture would miss them. Per D-10 all 6
      // targets diff against the same shared `${example}.png`. CommandPalette focuses
      // its search input on open, so its capture hides the blinking text caret.
      await expect(page).toHaveScreenshot(`${example}.png`, {
        animations: 'disabled',
        maxDiffPixels: 2,
        ...(example === 'CommandPaletteScreenshot' ? { caret: 'hide' as const } : {}),
      });
    });
  }
}
