import { test, expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// tests/visual-regression/package.json sets "type": "module", so __dirname is
// not defined here. Synthesize it from import.meta.url.
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * DARK-MODE pixel cell for the FlowCanvas (Rete.js) family (quick-260803-uwb; closes the
 * 260702-wws dark-mode deferral).
 *
 * WHY A SEPARATE SPEC (not matrix.spec.ts): the matrix runs EVERY cell under the browser
 * default (light) colour scheme and has no per-example media hook — a dark cell needs its
 * own `page.emulateMedia({ colorScheme: 'dark' })` frame applied BEFORE `goto`, which does
 * not fit the matrix's shared per-example settle pipeline. `overlay-screenshot.spec.ts` is
 * the shipped precedent for a pixel cell that lives in its own file with its own copied
 * baseline gate.
 *
 * WHAT IT GUARDS: FlowCanvas ships dark as a ZERO-IMPORT, OS-driven default — a top-level
 * scoped `@media (prefers-color-scheme: dark)` block redefining the `--rozie-flow-*` tokens
 * on `.rozie-flow-canvas` (FlowCanvas.rozie:3873-3910). Nothing in the VR suite had ever
 * rendered it, so a broken dark block would have gone green across the entire matrix.
 *
 * A NEW, SEPARATE BASELINE: `__screenshots__/FlowCanvasDarkScreenshot.png`. The shared
 * light baseline `FlowCanvasScreenshot.png` is the D-10 byte-identity invariant and is
 * UNTOUCHED — never regenerate it and never add `FlowCanvasScreenshot` to a bootstrap list
 * on account of this cell.
 *
 * Reference topology (D-10): the baseline is keyed by the `toHaveScreenshot` name arg only
 * (`snapshotPathTemplate: '__screenshots__/{arg}{ext}'`), so all 6 targets diff against the
 * SAME PNG. A target that "renders wrong but consistently" is still caught.
 *
 * BASELINES ARE LINUX-DOCKER-GENERATED (feedback_vr_linux_baselines): no macOS-rendered PNG
 * is committed. Until the Linux baseline lands, every cell here auto-fixmes via
 * `baselineExists()` (green-skipped, never red). Generate it with
 *   tools/ci-repro/vr.sh -u -b FlowCanvasDarkScreenshot -g 'rete-flow|FlowCanvasDark'
 * then verify with a plain (no -u, no -b) run.
 */

const TARGETS = ['vue', 'react', 'svelte', 'angular', 'solid', 'lit'] as const;
const EXAMPLES = ['FlowCanvasDarkScreenshot'] as const;

// Baseline-availability gate (per-example), copied from matrix.spec.ts /
// overlay-screenshot.spec.ts. When __screenshots__/<Name>.png is missing the cells for that
// example downgrade to test.fixme so the suite stays green until a Linux-Docker baseline
// regen lands the PNG.
//
// Bootstrap escape hatch: a brand-new example has a chicken-and-egg problem — its cell is
// test.fixme until its .png exists, but the .png can only be generated by running the cell
// with Playwright's `-u` (which does NOT override test.fixme). Set
// ROZIE_VR_BOOTSTRAP_BASELINE=<ExampleName> (comma-separated) to force-ungate for ONE `-u`
// pass. Used only by the Docker baseline-regen recipe; never set in CI.
const BOOTSTRAP_BASELINES = new Set(
  (process.env.ROZIE_VR_BOOTSTRAP_BASELINE ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
);
function baselineExists(name: string): boolean {
  if (BOOTSTRAP_BASELINES.has(name)) return true;
  return existsSync(resolve(__dirname, `../__screenshots__/${name}.png`));
}

for (const example of EXAMPLES) {
  const hasBaseline = baselineExists(example);
  for (const target of TARGETS) {
    const built = existsSync(
      resolve(__dirname, `../dist/${target}/host/entry.${target}.html`),
    );
    // Cell fixme-gates on EITHER the per-target build availability OR the per-example
    // baseline PNG presence (until the Linux-Docker regen lands).
    const runner = !built || !hasBaseline ? test.fixme : test;
    runner(`${example} · ${target}`, async ({ page }) => {
      // BEFORE goto: the component's dark tokens are resolved from the media query at
      // style time, and the imperative SVG reads them at draw time — emulating after the
      // mount would leave the first paint light.
      await page.emulateMedia({ colorScheme: 'dark' });
      await page.goto(`/?example=${example}&target=${target}`);

      const component = page.getByTestId('rozie-mount');
      await expect(component).toBeVisible();

      // Settle exactly as the shipped FlowCanvasScreenshot matrix cell does: the engine
      // mounts on $onMount, the vanilla render pipe fills the 3 node elements, and the
      // socket-position watcher drives the 2 connection paths. Both are engine-created DOM
      // (className set imperatively), so the classes are literal on every target and the
      // CSS locators pierce Lit's open shadow root.
      await expect(page.locator('.rozie-flow-node')).toHaveCount(3, { timeout: 15_000 });
      await expect(page.locator('.rozie-flow-connection__path')).toHaveCount(2, {
        timeout: 10_000,
      });

      // MANDATORY pre-clip proof that dark actually applied. Without it a bootstrap `-u`
      // pass that somehow ran in a light context would silently generate a LIGHT png and
      // bless it as the dark baseline — the one failure mode a first baseline cannot
      // recover from. `#0f172a` is the dark `--rozie-flow-bg`; light renders the
      // `#f7f8fa` fallback.
      await expect
        .poll(
          async () =>
            page
              .locator('.rozie-flow-canvas')
              .first()
              .evaluate((el) => getComputedStyle(el).backgroundColor),
          { timeout: 10_000, intervals: [100, 300, 600, 1000] },
        )
        .toBe('rgb(15, 23, 42)');

      // a short settle absorbs the final path-redraw reflow.
      await page.waitForTimeout(300);

      await expect(component).toHaveScreenshot(`${example}.png`, {
        maxDiffPixels: 2,
        animations: 'disabled',
      });
    });
  }
}
