import { test, expect } from '@playwright/test';
import { existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// tests/visual-regression/package.json sets "type": "module", so __dirname is
// not defined here. Synthesize it from import.meta.url.
const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * DARK-MODE pixel cell for the TipTap family (260927-a2v; closes the
 * 2026-09-27 dark-default gap).
 *
 * WHY A SEPARATE SPEC (not matrix.spec.ts): the matrix runs EVERY cell under the browser
 * default (light) colour scheme and has no per-example media hook — a dark cell needs its
 * own `page.emulateMedia({ colorScheme: 'dark' })` frame applied BEFORE `goto`, which does
 * not fit the matrix's shared per-example settle pipeline. `rete-flow-dark.spec.ts` is the
 * shipped precedent for a pixel cell that lives in its own file with its own copied
 * baseline gate.
 *
 * WHAT IT GUARDS: TipTap ships dark as a ZERO-IMPORT, OS-driven default — a
 * `:root { @media (prefers-color-scheme: dark) { :where(...) { ... } } }` block
 * redefining 15 `--rozie-tiptap-*` tokens on the private `--rtt-*` names
 * (TipTap.rozie, immediately after `.rozie-tiptap-count-value.over`). Nothing in the
 * VR suite had ever rendered it, so a broken dark block would have gone green across
 * the entire matrix.
 *
 * A NEW, SEPARATE BASELINE: `__screenshots__/TipTapDarkScreenshot.png`. The shared
 * light baseline `TipTapScreenshot.png` is UNTOUCHED — never regenerate it and never
 * add `TipTapScreenshot` to a bootstrap list on account of this cell.
 *
 * BASELINES ARE LINUX-DOCKER-GENERATED (feedback_vr_linux_baselines): no macOS-rendered PNG
 * is committed. Until the Linux baseline lands, every cell here auto-fixmes via
 * `baselineExists()` (green-skipped, never red). Generate it with
 *   tools/ci-repro/vr.sh -u -b TipTapDarkScreenshot -g 'tiptap-dark|TipTapDark'
 * then verify with a plain (no -u, no -b) run.
 */

const TARGETS = ['vue', 'react', 'svelte', 'angular', 'solid', 'lit'] as const;
const EXAMPLES = ['TipTapDarkScreenshot'] as const;

// Baseline-availability gate (per-example), copied from matrix.spec.ts /
// rete-flow-dark.spec.ts. When __screenshots__/<Name>.png is missing the cells for that
// example downgrade to test.fixme so the suite stays green until a Linux-Docker baseline
// regen lands the PNG.
//
// Bootstrap escape hatch: a brand-new example has a chicken-and-egg problem — its cell is
// test.fixme until its .png exists, but the .png can only be generated by running the cell
// with Playwright's `-u` (which does NOT override test.fixme). Set
// ROZIE_VR_BOOTSTRAP_BASELINE=<ExampleName> (comma-separated) to force-ungate for ONE `-u`
// pass. Used only by the Docker baseline-regen recipe; never set in CI.
const BOOTSTRAP_BASELINES = new Set(
  (process.env.ROZIE_VR_BOOTSTRAP_BASELINE ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),
);
function baselineExists(name: string): boolean {
  if (BOOTSTRAP_BASELINES.has(name)) return true;
  return existsSync(resolve(__dirname, `../__screenshots__/${name}.png`));
}

for (const example of EXAMPLES) {
  const hasBaseline = baselineExists(example);
  for (const target of TARGETS) {
    const built = existsSync(
      resolve(__dirname, `../dist/${target}/host/entry.${target}.html`),
    );
    // Cell fixme-gates on EITHER the per-target build availability OR the per-example
    // baseline PNG presence (until the Linux-Docker regen lands).
    const runner = !built || !hasBaseline ? test.fixme : test;
    runner(`${example} · ${target}`, async ({ page }) => {
      // BEFORE goto: the component's dark tokens are resolved from the media query at
      // style time — emulating after mount would leave the first paint light.
      await page.emulateMedia({ colorScheme: 'dark' });
      await page.goto(`/?example=${example}&target=${target}`);

      const component = page.getByTestId('rozie-mount');
      await expect(component).toBeVisible();

      // MANDATORY pre-clip proof that dark actually applied. Without it a bootstrap `-u`
      // pass that somehow ran in a light context would silently generate a LIGHT png and
      // bless it as the dark baseline — the one failure mode a first baseline cannot
      // recover from. `#1e293b` is the dark `--rtt-bg`; light renders the `white` fallback.
      await expect
        .poll(
          async () =>
            page
              .locator('.rozie-tiptap')
              .first()
              .evaluate((el) => getComputedStyle(el).backgroundColor),
          { timeout: 10_000, intervals: [100, 300, 600, 1000] },
        )
        .toBe('rgb(30, 41, 59)');

      // a short settle absorbs any final layout reflow.
      await page.waitForTimeout(300);

      await expect(component).toHaveScreenshot(`${example}.png`, {
        maxDiffPixels: 2,
        animations: 'disabled',
      });
    });
  }
}
