import { defineConfig, type Plugin } from 'vite';
import { dirname, resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import Rozie from '@rozie/unplugin/vite';

/*
 * Phase 41 Wave-0 De-Risk Probe — per-target build config.
 *
 * Modeled on tests/visual-regression/vite.config.ts (one Rozie({ target }) per
 * build; ROZIE_TARGET selects the column). Scoped to the engine-less
 * Probe/ProbeConsumer pair under packages/ui/rete/scripts/probe-41/. THROWAWAY.
 *
 * `root` is the VR dir (DEPS_DIR) so Vite's NATIVE resolver + each framework
 * plugin handle module resolution exactly as the real VR host (browser/import
 * conditions, svelte subpaths, solid-js/web client build). The per-target entry
 * HTML is generated by the driver INSIDE the VR dir (`.probe41-host/`) and
 * imports the probe entry .ts by absolute path. The Angular column wires
 * `prebuildExtraRoots: [PROBE41_DIR]` so the probe .rozie files get an AOT
 * disk-cache `.rozie.ts` (the analog of the VR config's reteSrc handling).
 */
type Target = 'vue' | 'react' | 'svelte' | 'angular' | 'solid' | 'lit';
const TARGET = (process.env.ROZIE_TARGET ?? 'vue') as Target;
const PROBE41_DIR = process.env.PROBE41_DIR ?? dirname(fileURLToPath(import.meta.url));
const DEPS_DIR = process.env.PROBE41_DEPS_DIR ?? PROBE41_DIR; // the VR package dir
const INPUT_HTML = process.env.PROBE41_INPUT_HTML as string; // generated by driver

// Angular-only: the AOT disk-cache prebuild emits `<PROBE41_DIR>/*.rozie.ts`
// files that import `@angular/core` etc.; those deps live under the VR package's
// node_modules, not beside the probe sources. Re-resolve bare imports from such
// cross-tree files via createRequire(DEPS_DIR). Verbatim shape from the VR
// config's resolveCrossTreeBareImports (the reteSrc handling).
function resolveCrossTreeBareImports(extraRoots: readonly string[]): Plugin {
  const requireFromVr = createRequire(resolve(DEPS_DIR, 'noop.js'));
  return {
    name: 'probe41:resolve-cross-tree-bare-imports',
    enforce: 'pre',
    resolveId(source, importer) {
      if (!importer) return null;
      if (
        source.startsWith('./') ||
        source.startsWith('../') ||
        source.startsWith('/') ||
        source.startsWith('\0')
      )
        return null;
      if (!extraRoots.some((root) => importer.startsWith(root))) return null;
      const queryIdx = source.indexOf('?');
      const bareSource = queryIdx === -1 ? source : source.slice(0, queryIdx);
      try {
        const pkgJsonPath = requireFromVr.resolve(`${bareSource}/package.json`);
        const pkg = JSON.parse(readFileSync(pkgJsonPath, 'utf8')) as {
          exports?: { '.'?: { import?: string } };
          module?: string;
        };
        const esmRel = pkg.exports?.['.']?.import ?? pkg.module;
        if (esmRel) return resolve(dirname(pkgJsonPath), esmRel);
      } catch {
        /* fall through */
      }
      try {
        return requireFromVr.resolve(bareSource);
      } catch {
        return null;
      }
    },
  };
}

async function frameworkPlugins(target: Target) {
  switch (target) {
    case 'vue': {
      const { default: vue } = await import('@vitejs/plugin-vue');
      return [
        vue({
          template: {
            compilerOptions: { isCustomElement: (tag: string) => tag.startsWith('rozie-') },
          },
        }),
      ];
    }
    case 'react': {
      const { default: react } = await import('@vitejs/plugin-react');
      return [react()];
    }
    case 'svelte': {
      const { svelte } = await import('@sveltejs/vite-plugin-svelte');
      return [svelte()];
    }
    case 'solid': {
      const { default: solid } = await import('vite-plugin-solid');
      return [solid()];
    }
    case 'angular': {
      const { default: angular } = await import('@analogjs/vite-plugin-angular');
      return [angular()];
    }
    case 'lit':
      return [];
    default:
      return [];
  }
}

export default defineConfig(async () => {
  return {
    root: DEPS_DIR,
    base: `/${TARGET}/`,
    plugins: [
      ...(TARGET === 'angular' ? [resolveCrossTreeBareImports([PROBE41_DIR])] : []),
      Rozie({
        target: TARGET,
        ...(TARGET === 'angular' ? { prebuildExtraRoots: [PROBE41_DIR] } : {}),
      }),
      ...(await frameworkPlugins(TARGET)),
    ],
    ...(TARGET === 'lit'
      ? {
          esbuild: {
            tsconfigRaw: {
              compilerOptions: { experimentalDecorators: true, useDefineForClassFields: false },
            },
          },
        }
      : {}),
    build: {
      outDir: resolve(PROBE41_DIR, 'dist', TARGET),
      emptyOutDir: true,
      minify: false,
      rollupOptions: { input: INPUT_HTML },
    },
  };
});
