/**
 * codegen.mjs — parse-once -> emit-6 -> render-READMEs for @rozie-ui/captcha.
 *
 * Generated by tools/scaffold-ui-family.mjs (engine shape). Pure GLUE over the
 * @rozie/core public API (compile / parse / lowerToIR / createDefaultRegistry).
 * NO compiler/emitter/IR change. If a compile() call emits an error-severity
 * diagnostic this script THROWS.
 *
 * BUILD-ORDER CONTRACT: writes each leaf src/<Name>.*, so it MUST run before the
 * bundled-leaf tsdown builds (turbo run build --force).
 *
 * AUTHOR NEXT STEPS:
 *   1. author src/Captcha.rozie
 *   2. fill scripts/event-manifest.mjs + scripts/handle-manifest.mjs to match
 *   3. run: node scripts/codegen.mjs
 */
import { cpSync, mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { compile, createDefaultRegistry, lowerToIR, parse } from '@rozie/core';
import { eventManifest } from './event-manifest.mjs';
import { handleManifest } from './handle-manifest.mjs';
import { renderReadme, validateDocsPropsTable } from './readme.mjs';

const BT = String.fromCharCode(96);
const NAME = "Captcha";
const SLUG = "captcha";
const STYLED = false;
const ENGINE = null;
const ENGINE_VERSION = null;

/** Vendor src/internal/ → leaf src/internal/ (excluding *.test.ts), if present. */
function copyInternal(leafSrc) {
  const src = resolve(ROOT, 'src/internal');
  if (!existsSync(src)) return;
  cpSync(src, resolve(leafSrc, 'internal'), {
    recursive: true,
    filter: (from) => !from.endsWith('.test.ts'),
  });
}

const ROOT = resolve(import.meta.dirname, '..');
const REPO_ROOT = resolve(ROOT, '..', '..', '..');
const FILENAME = NAME + '.rozie';
const SRC = resolve(ROOT, 'src', FILENAME);

const VUE_EXTERNALS = ENGINE ? ['vue', ENGINE, /^vue\//] : ['vue', /^vue\//];
const VUE_ENGINE_DEV_DEPS = ENGINE ? { [ENGINE]: ENGINE_VERSION } : {};

const TARGETS = {
  react: { dir: 'react', file: NAME + '.tsx', build: 'tsdown' },
  vue: {
    dir: 'vue',
    file: NAME + '.vue',
    build: 'source',
    externals: VUE_EXTERNALS,
    engineDevDeps: VUE_ENGINE_DEV_DEPS,
  },
  svelte: { dir: 'svelte', file: NAME + '.svelte', build: 'source' },
  angular: { dir: 'angular', file: NAME + '.ts', build: 'source' },
  solid: { dir: 'solid', file: NAME + '.tsx', build: 'tsdown' },
  lit: { dir: 'lit', file: NAME + '.ts', build: 'tsdown' },
};

function leafPkgName(dir) {
  const pkgPath = resolve(ROOT, 'packages', dir, 'package.json');
  return JSON.parse(readFileSync(pkgPath, 'utf8')).name;
}

const COMMON_VUE_BUILD_DEV_DEPS = {
  '@vitejs/plugin-vue': '^6',
  vite: '^8',
  'vite-plugin-css-injected-by-js': '^5',
  vue: '^3.5',
  'vue-tsc': '^3',
};

// Vue dual-packaging: ship BOTH a compiled drop-in (dist/index.mjs, CSS-inlined +
// dist/index.d.ts) AND the raw SFC (./source). Vue cannot use tsdown, so the build
// is Vite lib mode + @vitejs/plugin-vue + vite-plugin-css-injected-by-js. Patches
// the four Vue-leaf files idempotently each run; version is PRESERVED.
function emitVueDualPackaging({ leafDir, componentName, externals, engineDevDeps }) {
  const renderExternal = (e) => (e instanceof RegExp ? e.toString() : "'" + e + "'");
  const externalsLiteral = '[' + externals.map(renderExternal).join(', ') + ']';

  const viteConfig = [
    "import { defineConfig } from 'vite';",
    "import vue from '@vitejs/plugin-vue';",
    "import cssInjectedByJsPlugin from 'vite-plugin-css-injected-by-js';",
    '',
    '// Vue dual-packaging: compile the raw SFC to a drop-in dist/index.mjs via Vite',
    '// lib mode + @vitejs/plugin-vue. vite-plugin-css-injected-by-js inlines any SFC',
    '// scoped style into the JS. The runtime peers are externalized.',
    'export default defineConfig({',
    '  plugins: [vue(), cssInjectedByJsPlugin()],',
    '  build: {',
    "    outDir: 'dist',",
    '    emptyOutDir: true,',
    '    lib: {',
    "      entry: 'src/index.ts',",
    "      formats: ['es'],",
    "      fileName: () => 'index.mjs',",
    '    },',
    '    rollupOptions: {',
    '      external: ' + externalsLiteral + ',',
    '    },',
    '  },',
    '});',
    '',
  ].join('\n');
  writeFileSync(resolve(leafDir, 'vite.config.ts'), viteConfig);

  writeFileSync(
    resolve(leafDir, 'src', 'index.ts'),
    "export { default as " + componentName + " } from './" + componentName + ".vue';\n" +
      "export { default } from './" + componentName + ".vue';\n",
  );

  const vueTsconfig = {
    extends: '../../../../../tsconfig.base.json',
    compilerOptions: {
      noEmit: false,
      declaration: true,
      emitDeclarationOnly: true,
      outDir: 'dist',
      module: 'ESNext',
      target: 'ES2022',
      moduleResolution: 'bundler',
      skipLibCheck: true,
      strictNullChecks: false,
      exactOptionalPropertyTypes: false,
      noImplicitAny: false,
      lib: ['ES2022', 'DOM', 'DOM.Iterable'],
    },
    include: ['src'],
    exclude: ['dist', 'node_modules'],
  };
  writeFileSync(resolve(leafDir, 'tsconfig.json'), JSON.stringify(vueTsconfig, null, 2) + '\n');

  const pkgPath = resolve(leafDir, 'package.json');
  const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
  pkg.exports = {
    '.': { types: './dist/index.d.ts', import: './dist/index.mjs', default: './dist/index.mjs' },
    './source': {
      vue: './src/' + componentName + '.vue',
      default: './src/' + componentName + '.vue',
    },
  };
  pkg.files = ['dist', 'src'];
  pkg.sideEffects = false;
  pkg.scripts = {
    ...pkg.scripts,
    build: 'vite build && vue-tsc --declaration --emitDeclarationOnly',
    typecheck: 'vue-tsc --noEmit',
  };
  const mergedDevDeps = {
    ...(pkg.devDependencies ?? {}),
    ...COMMON_VUE_BUILD_DEV_DEPS,
    ...engineDevDeps,
  };
  pkg.devDependencies = Object.fromEntries(
    Object.keys(mergedDevDeps)
      .sort()
      .map((k) => [k, mergedDevDeps[k]]),
  );
  for (const depField of ['dependencies', 'devDependencies']) {
    const deps = pkg[depField];
    if (!deps) continue;
    for (const [n, ver] of Object.entries(deps)) {
      if (n.startsWith('@rozie/runtime-') && ver === 'workspace:*') deps[n] = 'workspace:^';
    }
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}

function main() {
  const source = readFileSync(SRC, 'utf8');

  const { ast } = parse(source, { filename: FILENAME });
  const { ir } = lowerToIR(ast, { modifierRegistry: createDefaultRegistry() });

  for (const ev of ir.emits) {
    if (!eventManifest[ev]) {
      throw new Error(
        'codegen: event "' + ev + '" is emitted by the source but has no entry in event-manifest.mjs',
      );
    }
  }
  for (const m of ir.expose) {
    if (!handleManifest[m.name]) {
      throw new Error(
        'codegen: method "' + m.name + '" is exposed by the source but has no entry in handle-manifest.mjs',
      );
    }
  }

  for (const [target, cfg] of Object.entries(TARGETS)) {
    const r = compile(source, { target, filename: FILENAME });
    const errs = r.diagnostics.filter((d) => d.severity === 'error');
    if (errs.length) {
      throw new Error(
        'codegen ' +
          target +
          ': compile emitted error diagnostics (SCOPE FENCE: do NOT edit any emitter — fix the codegen path):\n' +
          errs.map((e) => '  ' + e.code + ': ' + e.message).join('\n'),
      );
    }

    const leafSrc = resolve(ROOT, 'packages', cfg.dir, 'src');
    mkdirSync(leafSrc, { recursive: true });

    writeFileSync(resolve(leafSrc, cfg.file), r.code);

    // Vendor src/internal/ (the loadCaptchaApi loader) into the leaf so the
    // relative `./internal/loadCaptchaApi` import resolves in the compiled
    // output, on every target. Excludes *.test.ts (tests stay in the meta-pkg).
    copyInternal(leafSrc);

    if (target === 'vue') {
      emitVueDualPackaging({
        leafDir: resolve(ROOT, 'packages', cfg.dir),
        componentName: NAME,
        externals: cfg.externals,
        engineDevDeps: cfg.engineDevDeps,
      });
    }

    if (cfg.build === 'tsdown') {
      const namedAndDefault =
        "export { default as " + NAME + " } from './" + NAME + "';\n" +
        "export { default } from './" + NAME + "';\n";
      const barrel =
        (target === 'react' || target === 'solid') && ir.expose.length > 0
          ? namedAndDefault +
            '\n/** The ' +
            BT +
            '$expose' +
            BT +
            ' imperative handle received via ' +
            BT +
            'ref' +
            BT +
            ' — { ' +
            ir.expose.map((m) => m.name).join(', ') +
            ' }. */\n' +
            "export type { " + NAME + "Handle } from './" + NAME + "';\n"
          : namedAndDefault;
      writeFileSync(resolve(leafSrc, 'index.ts'), barrel);
    }

    if (target === 'react') {
      if (r.css) {
        if (!STYLED) {
          throw new Error(
            'codegen react: the source emitted CSS but this family was scaffolded UNSTYLED. ' +
              'Re-scaffold with --styled (wires the react .css copy + ambient decl) or remove the style block.',
          );
        }
        writeFileSync(resolve(leafSrc, NAME + '.css'), r.css);
      }
      if (r.types) writeFileSync(resolve(leafSrc, NAME + '.d.ts'), r.types);
    }

    const pkgName = leafPkgName(cfg.dir);
    const readme = renderReadme(target, ir, eventManifest, pkgName, handleManifest);
    writeFileSync(resolve(ROOT, 'packages', cfg.dir, 'README.md'), readme);

    cpSync(resolve(REPO_ROOT, 'LICENSE'), resolve(ROOT, 'packages', cfg.dir, 'LICENSE'));

    const sidecars =
      target === 'react' && STYLED ? ' (+ .css + .d.ts)' : target === 'react' ? ' (+ .d.ts)' : '';
    console.log('codegen: ' + target.padEnd(8) + ' -> ' + cfg.dir + '/src/' + cfg.file + sidecars + '  OK');
  }

  const guidePath = resolve(REPO_ROOT, 'docs/components/' + SLUG + '.md');
  if (existsSync(guidePath)) {
    const docs = readFileSync(guidePath, 'utf8');
    const result = validateDocsPropsTable(ir, docs);
    if (!result.ok) {
      throw new Error(
        'codegen: docs props-table validation DRIFT in ' +
          guidePath +
          ':\n' +
          result.errors.map((e) => '  - ' + e).join('\n'),
      );
    }
    console.log('codegen: docs props-table validation PASS — ' + result.checkedRows + ' rows match ir.props');
  } else {
    console.log('codegen: docs props-table validation SKIPPED — no docs/components/' + SLUG + '.md');
  }

  console.log('codegen: done — 6 targets emitted, 6 READMEs rendered.');
}

main();
