/**
 * README rendering + docs-table validation for @rozie-ui/captcha.
 * Generated by tools/scaffold-ui-family.mjs. Pure glue over the @rozie/core IR.
 *
 * Structural content (props/events/handle/slots tables) derives from a SINGLE
 * parse of Captcha.rozie. Only the USAGE / HANDLE_USAGE snippets below are
 * hand-authored PLACEHOLDERS — refine them for the real component API.
 */
const BT = String.fromCharCode(96);
const NAME = "Captcha";
const SLUG = "captcha";
const SCOPE = "@rozie-ui";
const SUMMARY = "Cross-framework CAPTCHA / bot-protection widget wrapping Google reCAPTCHA v2, hCaptcha, and Cloudflare Turnstile.";
const ENGINE_PEER = "";
const STYLESHEET_IMPORT = "";

export function renderPropType(typeAnnotation) {
  if (!typeAnnotation) return 'unknown';
  if (typeAnnotation.kind === 'identifier') return typeAnnotation.name;
  if (typeAnnotation.kind === 'literal') return String(typeAnnotation.value);
  if (typeAnnotation.name) return typeAnnotation.name;
  if (typeAnnotation.value !== undefined) return String(typeAnnotation.value);
  return 'unknown';
}

export function renderPropDefault(defaultValue) {
  if (defaultValue == null) return '—';
  const node = defaultValue;
  switch (node.type) {
    case 'NullLiteral':
      return 'null';
    case 'BooleanLiteral':
      return String(node.value);
    case 'NumericLiteral':
      return String(node.value);
    case 'StringLiteral':
      return JSON.stringify(node.value);
    case 'ArrayExpression':
      return node.elements && node.elements.length ? '[…]' : '[]';
    case 'ObjectExpression':
      return node.properties && node.properties.length ? '{…}' : '{}';
    case 'ArrowFunctionExpression': {
      const b = node.body;
      if (b && b.type === 'ArrayExpression') return b.elements && b.elements.length ? '[…]' : '[]';
      if (b && b.type === 'ObjectExpression') return b.properties && b.properties.length ? '{…}' : '{}';
      return '() => …';
    }
    case 'Identifier':
      return node.name;
    default:
      return String(node.type);
  }
}

function renderSlotName(n) {
  return n === '' ? '(default)' : n;
}

function slotParams(slot) {
  return (slot.params || []).map((p) => p.name).join(', ');
}

const FRAMEWORK_PEER_LABEL = {
  react: 'react + react-dom',
  vue: 'vue',
  svelte: 'svelte',
  angular: '@angular/core + @angular/common',
  solid: 'solid-js',
  lit: 'lit',
};

// Per-framework usage PLACEHOLDERS — refine for the real component props/events.
// Real per-framework consumption snippets. `token` is two-way (the verified
// response); `@verify` fires `{ token, provider }`. Swap `your-site-key` for the
// key from your provider dashboard, and verify the token server-side.
export const USAGE = {
  react: {
    lang: 'tsx',
    code: `import { useState } from 'react';
import { Captcha } from '@rozie-ui/captcha-react';

export function Demo() {
  const [token, setToken] = useState('');
  return (
    <Captcha
      provider="recaptcha"
      sitekey="your-site-key"
      token={token}
      onTokenChange={setToken}
      onVerify={(e) => console.log('verified', e.token)}
    />
  );
}`,
  },
  vue: {
    lang: 'vue',
    code: `<script setup lang="ts">
import { ref } from 'vue';
import Captcha from '@rozie-ui/captcha-vue';

const token = ref('');
</script>

<template>
  <Captcha
    provider="recaptcha"
    sitekey="your-site-key"
    v-model:token="token"
    @verify="(e) => console.log('verified', e.token)"
  />
</template>`,
  },
  svelte: {
    lang: 'svelte',
    code: `<script lang="ts">
  import Captcha from '@rozie-ui/captcha-svelte';
  let token = $state('');
</script>

<Captcha
  provider="turnstile"
  sitekey="your-site-key"
  bind:token
  onverify={(e) => console.log('verified', e.token)}
/>`,
  },
  angular: {
    lang: 'ts',
    code: `import { Component } from '@angular/core';
import { Captcha } from '@rozie-ui/captcha-angular';

@Component({
  selector: 'app-demo',
  standalone: true,
  imports: [Captcha],
  template: \`<Captcha provider="recaptcha" sitekey="your-site-key" [(token)]="token" (verify)="onVerify($event)" />\`,
})
export class DemoComponent {
  token = '';
  onVerify(e: { token: string }) { console.log('verified', e.token); }
}`,
  },
  solid: {
    lang: 'tsx',
    code: `import { createSignal } from 'solid-js';
import { Captcha } from '@rozie-ui/captcha-solid';

export function Demo() {
  const [token, setToken] = createSignal('');
  return (
    <Captcha
      provider="recaptcha"
      sitekey="your-site-key"
      token={token()}
      onTokenChange={setToken}
      onVerify={(e) => console.log('verified', e.token)}
    />
  );
}`,
  },
  lit: {
    lang: 'ts',
    code: `import '@rozie-ui/captcha-lit';

// <rozie-captcha> is a custom element.
const el = document.querySelector('rozie-captcha');
el.provider = 'turnstile';
el.sitekey = 'your-site-key';
el.addEventListener('verify', (e) => console.log('verified', e.detail.token));`,
  },
};

// RecaptchaV3 per-framework usage snippets. v3 is imperative-first: there is no
// widget — call `execute(action?)` (resolves a `Promise<token>`) right before you
// submit, attach the token to the request, verify the score server-side. The
// component is the NAMED export `RecaptchaV3`; `token` is two-way; `@verify` fires
// `{ token, action }`. These are extra module constants consumed only inside
// renderReadme — they are NOT folded into the exported `USAGE` (which stays
// Captcha-shaped for the gen-usage-pages.mjs contract).
export const RECAPTCHA_V3_USAGE = {
  react: {
    lang: 'tsx',
    code: `import { useRef } from 'react';
import { RecaptchaV3, type RecaptchaV3Handle } from '@rozie-ui/captcha-react';

export function SignupForm() {
  const captcha = useRef<RecaptchaV3Handle>(null);
  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const token = await captcha.current?.execute('signup'); // fresh token for THIS action
    await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
  };
  return (
    <form onSubmit={onSubmit}>
      {/* … fields … */}
      <RecaptchaV3 ref={captcha} sitekey="your-site-key" action="signup" />
      <button type="submit">Sign up</button>
    </form>
  );
}`,
  },
  vue: {
    lang: 'vue',
    code: `<script setup lang="ts">
import { ref } from 'vue';
import { RecaptchaV3 } from '@rozie-ui/captcha-vue';

const captcha = ref();
const submit = async () => {
  const token = await captcha.value.execute('signup'); // fresh token for THIS action
  await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
};
</script>

<template>
  <form @submit.prevent="submit">
    <!-- … fields … -->
    <RecaptchaV3 ref="captcha" sitekey="your-site-key" action="signup" />
    <button type="submit">Sign up</button>
  </form>
</template>`,
  },
  svelte: {
    lang: 'svelte',
    code: `<script lang="ts">
  import { RecaptchaV3 } from '@rozie-ui/captcha-svelte';
  let captcha;
  const submit = async () => {
    const token = await captcha.execute('signup'); // fresh token for THIS action
    await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
  };
</script>

<form on:submit|preventDefault={submit}>
  <!-- … fields … -->
  <RecaptchaV3 bind:this={captcha} sitekey="your-site-key" action="signup" />
  <button type="submit">Sign up</button>
</form>`,
  },
  angular: {
    lang: 'ts',
    code: `import { Component, viewChild } from '@angular/core';
import { RecaptchaV3 } from '@rozie-ui/captcha-angular';

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [RecaptchaV3],
  template: \`
    <form (submit)="submit($event)">
      <!-- … fields … -->
      <RecaptchaV3 sitekey="your-site-key" action="signup" />
      <button type="submit">Sign up</button>
    </form>
  \`,
})
export class SignupComponent {
  captcha = viewChild(RecaptchaV3);
  async submit(e: Event) {
    e.preventDefault();
    const token = await this.captcha()!.execute('signup'); // fresh token for THIS action
    await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
  }
}`,
  },
  solid: {
    lang: 'tsx',
    code: `import { RecaptchaV3, type RecaptchaV3Handle } from '@rozie-ui/captcha-solid';

export function SignupForm() {
  let captcha: RecaptchaV3Handle | undefined;
  const submit = async (e: Event) => {
    e.preventDefault();
    const token = await captcha?.execute('signup'); // fresh token for THIS action
    await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
  };
  return (
    <form onSubmit={submit}>
      {/* … fields … */}
      <RecaptchaV3 ref={(h) => (captcha = h)} sitekey="your-site-key" action="signup" />
      <button type="submit">Sign up</button>
    </form>
  );
}`,
  },
  lit: {
    lang: 'ts',
    code: `import { RecaptchaV3 } from '@rozie-ui/captcha-lit';

// <rozie-recaptcha-v3> is a custom element; the element IS the handle.
const captcha = document.querySelector('rozie-recaptcha-v3') as RecaptchaV3;
async function submit() {
  const token = await captcha.execute('signup'); // fresh token for THIS action
  await fetch('/signup', { method: 'POST', body: JSON.stringify({ token }) });
}`,
  },
};

const ANGULAR_FORMS_USAGE = {
  lang: 'ts',
  code: [
    "import { Component } from '@angular/core';",
    "import { ReactiveFormsModule, FormControl } from '@angular/forms';",
    'import { ' + NAME + " } from '" + SCOPE + '/' + SLUG + "-angular';",
    '',
    '@Component({',
    "  selector: 'app-form',",
    '  standalone: true,',
    '  imports: [' + NAME + ', ReactiveFormsModule],',
    '  template: ' + JSON.stringify('<' + NAME + ' [formControl]="ctrl" />') + ',',
    '})',
    'export class FormComponent {',
    "  ctrl = new FormControl('');",
    '}',
  ].join('\n'),
};

// Per-framework "how to obtain the imperative handle" PLACEHOLDERS (Phase 21 $expose).
export const HANDLE_USAGE = {
  react: {
    lang: 'tsx',
    code: [
      "import { useRef } from 'react';",
      'import { ' + NAME + ', type ' + NAME + "Handle } from '" + SCOPE + '/' + SLUG + "-react';",
      '',
      'const handle = useRef<' + NAME + 'Handle>(null);',
      '// <' + NAME + ' ref={handle} provider="recaptcha" sitekey="your-site-key" />',
      '// handle.current?.reset();        // clear + reset the widget',
      '// handle.current?.execute();      // invisible / programmatic challenge',
      '// handle.current?.getResponse();  // read the current token',
    ].join('\n'),
  },
  vue: {
    lang: 'vue',
    code: [
      '<script setup>',
      "import { ref } from 'vue';",
      'const handle = ref();',
      '</script>',
      '',
      '<template>',
      '  <' + NAME + ' ref="handle" />',
      '</template>',
    ].join('\n'),
  },
  svelte: {
    lang: 'svelte',
    code: ['<script>', '  let handle;', '</script>', '', '<' + NAME + ' bind:this={handle} />'].join(
      '\n',
    ),
  },
  angular: {
    lang: 'ts',
    code: [
      '@Component({ /* ... */ })',
      'export class DemoComponent {',
      '  @ViewChild(' + NAME + ') handle!: ' + NAME + ';',
      '}',
    ].join('\n'),
  },
  solid: {
    lang: 'tsx',
    code: [
      'import { ' + NAME + ', type ' + NAME + "Handle } from '" + SCOPE + '/' + SLUG + "-solid';",
      '',
      'let handle: ' + NAME + 'Handle | undefined;',
      '// <' + NAME + ' ref={(h) => (handle = h)} />',
    ].join('\n'),
  },
  lit: {
    lang: 'ts',
    code: [
      '// The custom element IS the handle — its exposed methods are public element methods.',
      "document.querySelector('rozie-" + SLUG + "');",
    ].join('\n'),
  },
};

// RecaptchaV3 "how to grab the imperative handle + call execute()" per framework.
// Extra module constants consumed only inside renderReadme; NOT exported into the
// gen-usage-pages USAGE/HANDLE_USAGE contract (that stays Captcha-shaped).
export const RECAPTCHA_V3_HANDLE_USAGE = {
  react: {
    lang: 'tsx',
    code: [
      "import { useRef } from 'react';",
      "import { RecaptchaV3, type RecaptchaV3Handle } from '" + SCOPE + '/' + SLUG + "-react';",
      '',
      'const handle = useRef<RecaptchaV3Handle>(null);',
      '// <RecaptchaV3 ref={handle} sitekey="your-site-key" action="submit" />',
      '// const token = await handle.current?.execute();          // uses the action prop',
      "// const token = await handle.current?.execute('login');   // override for this call",
    ].join('\n'),
  },
  vue: {
    lang: 'vue',
    code: [
      '<script setup>',
      "import { ref } from 'vue';",
      'const handle = ref();',
      "// const token = await handle.value.execute('submit');",
      '</script>',
      '',
      '<template>',
      '  <RecaptchaV3 ref="handle" sitekey="your-site-key" />',
      '</template>',
    ].join('\n'),
  },
  svelte: {
    lang: 'svelte',
    code: [
      '<script>',
      '  let handle;',
      "  // const token = await handle.execute('submit');",
      '</script>',
      '',
      '<RecaptchaV3 bind:this={handle} sitekey="your-site-key" />',
    ].join('\n'),
  },
  angular: {
    lang: 'ts',
    code: [
      '@Component({ /* ... */ })',
      'export class DemoComponent {',
      '  handle = viewChild(RecaptchaV3);',
      "  // const token = await this.handle()!.execute('submit');",
      '}',
    ].join('\n'),
  },
  solid: {
    lang: 'tsx',
    code: [
      "import { RecaptchaV3, type RecaptchaV3Handle } from '" + SCOPE + '/' + SLUG + "-solid';",
      '',
      'let handle: RecaptchaV3Handle | undefined;',
      '// <RecaptchaV3 ref={(h) => (handle = h)} sitekey="your-site-key" />',
      "// const token = await handle?.execute('submit');",
    ].join('\n'),
  },
  lit: {
    lang: 'ts',
    code: [
      '// The custom element IS the handle — execute() is a public element method.',
      "const el = document.querySelector('rozie-recaptcha-v3');",
      "// const token = await el.execute('submit');",
    ].join('\n'),
  },
};

// Per-component usage/handle-usage lookup (selected by component name inside
// renderReadme). Captcha keeps its exported USAGE/HANDLE_USAGE; RecaptchaV3 rides
// its own (un-exported) maps.
const USAGE_BY_COMPONENT = { Captcha: USAGE, RecaptchaV3: RECAPTCHA_V3_USAGE };
const HANDLE_USAGE_BY_COMPONENT = { Captcha: HANDLE_USAGE, RecaptchaV3: RECAPTCHA_V3_HANDLE_USAGE };

/**
 * Render one leaf README documenting EVERY component in `components`
 * (`[{ name, ir }, ...]`, primary first). Intro + Install are rendered once; then
 * one `## <Name>` section per component (Usage / Angular-forms / Props / Events /
 * Imperative handle / Slots). `eventManifest` / `handleManifest` are the
 * per-component-KEYED maps ({ Captcha:{...}, RecaptchaV3:{...} }), indexed here by
 * component name. Called ONCE PER TARGET.
 */
export function renderReadme(target, components, eventManifest, pkgName, handleManifest = {}) {
  const c = (s) => BT + s + BT;
  const fence = (lang) => BT + BT + BT + lang;
  const close = BT + BT + BT;
  const lines = [];

  const primary = components[0];

  lines.push('# ' + pkgName);
  lines.push('');
  lines.push(
    'Idiomatic **' +
      target +
      '** ' +
      c(NAME) +
      ' — ' +
      SUMMARY +
      ' Compiled from one [Rozie](https://github.com/One-Learning-Community/rozie.js) source. ' +
      'This package is generated; do not edit ' +
      c('src/') +
      ' by hand.',
  );
  if (components.length > 1) {
    const others = components.slice(1).map((co) => c(co.name)).join(', ');
    lines.push('');
    lines.push(
      'This package ships ' +
        c(primary.name) +
        ' (the default export) alongside ' +
        others +
        ' (named export' +
        (components.length > 2 ? 's' : '') +
        ').',
    );
  }
  lines.push('');

  lines.push('## Install');
  lines.push('');
  lines.push(fence('bash'));
  lines.push('npm i ' + pkgName);
  lines.push(close);
  lines.push('');
  const peerLabel = ENGINE_PEER
    ? c(ENGINE_PEER) + ' + ' + c(FRAMEWORK_PEER_LABEL[target])
    : c(FRAMEWORK_PEER_LABEL[target]);
  lines.push(
    'Peer dependencies: ' +
      peerLabel +
      '.' +
      (STYLESHEET_IMPORT ? ' Also import ' + c(STYLESHEET_IMPORT) + ' once in your app.' : ''),
  );
  lines.push('');

  // One section per component (primary first). For a single-component family the
  // section heading still renders (`## <Name>`) — harmless and self-documenting.
  for (const comp of components) {
    const ir = comp.ir;
    const usage = (USAGE_BY_COMPONENT[comp.name] ?? {})[target];
    if (!usage) {
      throw new Error(
        'renderReadme: no usage snippet for component "' + comp.name + '" target "' + target + '"',
      );
    }
    const evManifest = eventManifest[comp.name];
    if (!evManifest) {
      throw new Error('renderReadme: no event-manifest entry for component "' + comp.name + '"');
    }
    const hManifest = handleManifest[comp.name] ?? {};

    lines.push('## ' + comp.name);
    lines.push('');

    lines.push('### Usage');
    lines.push('');
    lines.push(fence(usage.lang));
    lines.push(usage.code);
    lines.push(close);
    lines.push('');

    const modelProps = ir.props.filter((p) => p.isModel);
    if (target === 'angular' && modelProps.length === 1) {
      const modelProp = modelProps[0];
      lines.push('### Angular forms');
      lines.push('');
      lines.push(
        'The generated class implements ' +
          c('ControlValueAccessor') +
          ' — the ' +
          c(modelProp.name) +
          ' model prop is the control value — so it binds to template-driven and reactive ' +
          'forms directives directly:',
      );
      lines.push('');
      lines.push(fence(ANGULAR_FORMS_USAGE.lang));
      lines.push(ANGULAR_FORMS_USAGE.code);
      lines.push(close);
      lines.push('');
    }

    lines.push('### Props');
    lines.push('');
    lines.push('| Name | Type | Default | Two-way (model) | Required |');
    lines.push('| --- | --- | --- | :---: | :---: |');
    for (const p of ir.props) {
      const type = renderPropType(p.typeAnnotation);
      const def = renderPropDefault(p.defaultValue);
      lines.push(
        '| ' +
          c(p.name) +
          ' | ' +
          c(type) +
          ' | ' +
          c(def) +
          ' | ' +
          (p.isModel ? '✓' : '') +
          ' | ' +
          (p.required ? '✓' : '') +
          ' |',
      );
    }
    lines.push('');

    lines.push('### Events');
    lines.push('');
    lines.push('| Event | Description |');
    lines.push('| --- | --- |');
    for (const ev of ir.emits) {
      const desc = evManifest[ev];
      if (!desc) {
        throw new Error(
          'renderReadme: event "' + ev + '" of ' + comp.name + ' missing from event-manifest',
        );
      }
      lines.push('| ' + c(ev) + ' | ' + desc + ' |');
    }
    lines.push('');

    if (ir.expose && ir.expose.length > 0) {
      const handleUsage = (HANDLE_USAGE_BY_COMPONENT[comp.name] ?? {})[target];
      if (!handleUsage) {
        throw new Error(
          'renderReadme: no handle-usage snippet for component "' + comp.name + '" target "' + target + '"',
        );
      }
      lines.push('### Imperative handle');
      lines.push('');
      lines.push(
        'This component exposes imperative methods (declared once in the Rozie source via ' +
          c('$expose') +
          '). Grab a handle with the native ref mechanism and call them directly:',
      );
      lines.push('');
      lines.push(fence(handleUsage.lang));
      lines.push(handleUsage.code);
      lines.push(close);
      lines.push('');
      lines.push('| Method | Description |');
      lines.push('| --- | --- |');
      for (const m of ir.expose) {
        const desc = hManifest[m.name];
        if (!desc) {
          throw new Error(
            'renderReadme: exposed method "' + m.name + '" of ' + comp.name + ' missing from handle-manifest',
          );
        }
        lines.push('| ' + c(m.name) + ' | ' + desc + ' |');
      }
      lines.push('');
    }

    if (ir.slots && ir.slots.length > 0) {
      lines.push('### Slots');
      lines.push('');
      lines.push('| Slot | Params |');
      lines.push('| --- | --- |');
      for (const s of ir.slots) lines.push('| ' + renderSlotName(s.name) + ' | ' + slotParams(s) + ' |');
      lines.push('');
    }
  }

  return lines.join('\n');
}

export function validateDocsPropsTable(ir, docsMarkdown) {
  const errors = [];
  const propsHeadingIdx = docsMarkdown.indexOf('### Props');
  if (propsHeadingIdx === -1) {
    return { ok: false, errors: ['docs: "### Props" heading not found'], checkedRows: 0 };
  }
  const afterHeading = docsMarkdown.slice(propsHeadingIdx + '### Props'.length);
  const nextHeadingIdx = afterHeading.search(/\n#{1,3}\s/);
  const section = nextHeadingIdx === -1 ? afterHeading : afterHeading.slice(0, nextHeadingIdx);

  const docRows = new Map();
  const nameRe = new RegExp('^' + BT + '([^' + BT + ']+)' + BT + '$');
  const btRe = new RegExp(BT, 'g');
  for (const rawLine of section.split('\n')) {
    const line = rawLine.trim();
    if (!line.startsWith('|')) continue;
    const cells = line
      .split(/(?<!\\)\|/)
      .slice(1, -1)
      .map((cc) => cc.replace(/\\\|/g, '|').trim());
    if (cells.length < 3) continue;
    const nameMatch = cells[0].match(nameRe);
    if (!nameMatch) continue;
    docRows.set(nameMatch[1], { type: cells[1], def: cells[2] });
  }

  const irNames = new Set(ir.props.map((p) => p.name));
  const docNames = new Set(docRows.keys());
  for (const n of irNames) {
    if (!docNames.has(n)) errors.push('docs missing prop row: "' + n + '" (present in source)');
  }
  for (const n of docNames) {
    if (!irNames.has(n)) errors.push('docs has stale prop row: "' + n + '" (absent from source)');
  }

  const stripCode = (s) => s.replace(btRe, '').trim();
  for (const p of ir.props) {
    const doc = docRows.get(p.name);
    if (!doc) continue;
    const irType = renderPropType(p.typeAnnotation);
    const docType = stripCode(doc.type);
    const docTypeTokens = docType.split('|').map((t) => t.trim());
    if (!docTypeTokens.includes(irType)) {
      errors.push('prop "' + p.name + '": type drift — source ' + irType + ', docs ' + docType);
    }
    const irDef = renderPropDefault(p.defaultValue);
    const docDef = stripCode(doc.def);
    if (irDef !== '—' && docDef !== irDef) {
      errors.push('prop "' + p.name + '": default drift — source ' + irDef + ', docs ' + docDef);
    }
  }

  return { ok: errors.length === 0, errors, checkedRows: docRows.size };
}
