/**
 * emitTypes (Solid) — Phase 22 Plan 22-03 (typed `.rozie` imports).
 *
 * Emits a sibling Solid `.d.rozie.ts` from an `IRComponent`. Mirrors React's
 * `emitTypes.ts` structure but:
 *   - consumes the Plan-02 core-shared `renderPropsInterface` for the
 *     framework-AGNOSTIC props-interface body (single source of truth — see the
 *     LOCKED CONTRACT in 22-02-SUMMARY.md),
 *   - swaps ONLY the framework default-export idiom to Solid's inline
 *     `import('solid-js').Component<<Name>Props>` form (PATTERNS Pattern 2
 *     table).
 *
 * Output shape (canonical):
 *
 *   export interface CounterProps {
 *     value?: number;
 *     defaultValue?: number;
 *     onValueChange?: (next: number) => void;
 *     step?: number;
 *   }
 *   declare const Counter: import('solid-js').Component<CounterProps>;
 *   export default Counter;
 *
 * Handle interface (Phase 21 $expose, REQ-2): when `ir.expose` is non-empty the
 * `<Name>Handle` interface is synthesized via the core-shared
 * `synthesizeHandleType` and exported alongside the default export. When empty,
 * NO handle interface is emitted. (Solid already consumes `synthesizeHandleType`
 * for its inline `ref?: (h: <Name>Handle) => void` prop — see the helper's own
 * docstring.)
 *
 * Slot idiom decision (Solid): Solid slot props are children-returning thunks
 * whose return type is `JSX.Element`. The slot-children token is `'JSX.Element'`
 * (the example token in the LOCKED CONTRACT). The inline `import('solid-js')`
 * default-export form avoids a value import; when the component declares slots
 * the sidecar adds `import type { JSX } from 'solid-js'` so `JSX.Element`
 * resolves (an unresolved `JSX` would degrade slot props to `any`).
 *
 * NO do-not-edit header / source-hash is prepended here — the Wave-3 sidecar
 * WRITER owns that.
 *
 * @experimental — shape may change before v1.0
 */
import type { IRComponent } from '@rozie/core';
import { renderPropsInterface } from '@rozie/core';
import { emitSlotDecl } from './emitSlotDecl.js';
import { slotsRecordLine } from './emitPropsInterface.js';
// `synthesizeHandleType` is not yet in the `@rozie/core` barrel — import it
// relatively as React's emitTypes.ts does.
import { synthesizeHandleType } from '../../../../core/src/codegen/synthesizeHandleType.js';
import { handleInterfaceName, propsInterfaceName } from '../../../../core/src/codegen/generatedTypeNames.js';
import { SOLID_JSX_TYPE_IMPORT } from '../../../../core/src/codegen/targetModuleImports.js';

/**
 * Options controlling Solid `.d.rozie.ts` emission.
 *
 * @experimental — shape may change before v1.0
 */
export interface EmitSolidTypesOptions {
  /**
   * D-85 generic preservation: when set, emits
   * `export interface FooProps<T, ...>` and the inline
   * `import('solid-js').Component<FooProps<T, ...>>` default export.
   */
  genericParams?: string[];
}

/**
 * Build a Solid `.d.rozie.ts` source string from an IRComponent.
 *
 * @public — consumed by the Wave-3 unplugin sidecar emit + CLI fallback.
 */
export function emitSolidTypes(ir: IRComponent, opts: EmitSolidTypesOptions = {}): string {
  const exposed = (ir.expose ?? []).length > 0;
  const handleInterface = exposed ? synthesizeHandleType(ir, handleInterfaceName(ir.name)) : null;

  const generics =
    opts.genericParams && opts.genericParams.length > 0 ? `<${opts.genericParams.join(', ')}>` : '';

  const lines: string[] = [];

  // Slot surface generated by the SAME function the compiled module uses
  // (emitSlotDecl), so the sidecar can never drift from the module.
  const slotDecl = emitSlotDecl(ir);
  // `JSX.Element` (slot fields) must resolve — an unresolved `JSX` silently
  // degrades every slot prop to `any` in a consumer with skipLibCheck.
  if (ir.slots.length > 0) {
    lines.push(SOLID_JSX_TYPE_IMPORT);
    lines.push('');
  }
  for (const iface of slotDecl.ctxInterfaces) lines.push(iface);
  if (slotDecl.ctxInterfaces.length > 0) lines.push('');

  lines.push(
    renderPropsInterface(ir, {
      ...(opts.genericParams ? { genericParams: opts.genericParams } : {}),
      slotChildrenType: 'JSX.Element',
      slotSurface: {
        // Internal `// D-131 ...` comments are not public-sidecar content.
        fields: slotDecl.fields.filter((l) => !l.trimStart().startsWith('//')),
        ...(slotsRecordLine(ir) !== undefined ? { recordLine: slotsRecordLine(ir)! } : {}),
      },
      target: 'solid',
      // Typed public surface phase 3 — mirror the inline interface's
      // `extends Omit<ComponentProps<tag>, …>` in the public sidecar.
      htmlAttrs: 'solid',
      includeTypesBlock: true,
    }),
  );
  lines.push('');

  if (exposed && handleInterface) {
    lines.push(`export ${handleInterface}`);
    lines.push('');
  }

  lines.push(`declare const ${ir.name}: import('solid-js').Component<${propsInterfaceName(ir.name)}${generics}>;`);
  lines.push(`export default ${ir.name};`);
  lines.push('');
  return lines.join('\n');
}
