// @vitest-environment happy-dom
/**
 * args.behavior.test.ts — mount-and-drive behavioral proof of inline command
 * arguments (feature #12, ARGS-SURFACE/ARGS-SUBMIT/ARGS-ESCAPE/ARGS-RENDER).
 *
 * RED-first: authored BEFORE the CommandPalette.rozie args-surface change was
 * regenerated into packages/vue/src/CommandPalette.vue — run against the
 * PRE-feature emitted leaf this suite was RED (no args surface renders at
 * all, verified by hand before the `.rozie` evolution). After the `.rozie`
 * evolution + `node scripts/codegen.mjs` regen it is GREEN.
 *
 * Mirrors packages/ui/command-palette/tests/groupcap-actions.behavior.test.ts:
 * mount the REAL committed emitted packages/vue/src/CommandPalette.vue
 * (transformed by @vitejs/plugin-vue, happy-dom supplies the DOM, the
 * vendored @rozie-ui/combobox-vue supplies the combobox render), drive it
 * via real DOM events, and assert on the rendered DOM + the `@select`
 * payload.
 *
 * Selection commit note: the vendored <Combobox> commits a row on
 * `@mousedown.prevent` (Combobox.rozie), NOT `@click` — `selectRow()` below
 * dispatches `mousedown` accordingly.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from CommandPalette.rozie) — @vitejs/plugin-vue transforms this SFC into a
// mountable component.
import CommandPalette from '../packages/vue/src/CommandPalette.vue';

function makeItems() {
  return [
    {
      id: 'create-page',
      label: 'Create page',
      args: [
        { id: 'name', placeholder: 'Page name', required: true },
        { id: 'template', placeholder: 'Template', default: 'blank' },
      ],
    },
    { id: 'plain', label: 'Plain command' },
    {
      id: 'source-and-args',
      label: 'Source and args',
      args: [{ id: 'q', placeholder: 'Query', required: true }],
      source: () => [{ id: 'nested', label: 'Nested' }],
    },
  ];
}

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

function mountPalette(extraProps: Record<string, unknown> = {}) {
  const openRef = ref(true);
  const queryRef = ref('');
  const selectPayloads: unknown[] = [];
  const navigatePayloads: unknown[] = [];
  const backCount = { n: 0 };
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(CommandPalette, {
        open: openRef.value,
        'onUpdate:open': (v: boolean) => {
          openRef.value = v;
        },
        query: queryRef.value,
        'onUpdate:query': (v: string) => {
          queryRef.value = v;
        },
        items: makeItems(),
        idBase: 'args-behavior-test',
        onSelect: (payload: unknown) => selectPayloads.push(payload),
        onNavigate: (payload: unknown) => navigatePayloads.push(payload),
        onBack: () => {
          backCount.n += 1;
        },
        ...extraProps,
      }),
  });
  app.mount(host);
  return { app, host, selectPayloads, navigatePayloads, backCount };
}

/** Focus the combobox's search input (opens the popup) and flush. */
async function openPopup(host: HTMLElement) {
  const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
  input.dispatchEvent(new Event('focus'));
  await nextTick();
  await Promise.resolve();
  return input;
}

function optionRowFor(host: HTMLElement, label: string): HTMLElement {
  const row = Array.from(host.querySelectorAll('[role="option"]')).find((el) =>
    el.textContent?.includes(label),
  ) as HTMLElement | undefined;
  if (!row) throw new Error(`no option row found for "${label}"`);
  return row;
}

/** Commits a row — the vendored <Combobox> selects on @mousedown.prevent. */
function selectRow(row: HTMLElement) {
  row.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, cancelable: true }));
}

/** Awaits one real animation frame — openArgsSurface/reopenComboboxPopup
 * defer their focus move a frame (rAF) so the surface has mounted first. */
function nextFrame(): Promise<void> {
  return new Promise((resolve) => {
    if (typeof requestAnimationFrame !== 'undefined') requestAnimationFrame(() => resolve());
    else setTimeout(resolve, 0);
  });
}

describe('CommandPalette inline command arguments (behavioral, RED-first)', () => {
  it('auto-entry: selecting an item with args renders the args surface, focuses the first field, dims the list — and does NOT emit @select yet', async () => {
    const { app, host, selectPayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const argsSurface = host.querySelector('[data-testid="command-palette-args"]');
    expect(argsSurface).not.toBeNull();
    expect(argsSurface?.getAttribute('role')).toBe('group');

    const firstInput = host.querySelector('[data-command-palette-args] input') as HTMLInputElement;
    expect(firstInput).not.toBeNull();
    expect(document.activeElement).toBe(firstInput);

    const listRegion = host.querySelector('.rozie-command-palette-list-region');
    expect(listRegion?.getAttribute('aria-hidden')).toBe('true');

    expect(selectPayloads.length).toBe(0);

    app.unmount();
  });

  it('submit payload: filling the field and pressing Enter emits @select with a trimmed additive `args` key', async () => {
    const { app, host, selectPayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const inputs = host.querySelectorAll('[data-command-palette-args] input');
    const nameInput = inputs[0] as HTMLInputElement;
    nameInput.value = '  My Page  ';
    nameInput.dispatchEvent(new Event('input', { bubbles: true }));
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
    await nextTick();

    expect(selectPayloads.length).toBe(1);
    const payload = selectPayloads[0] as { item: { id: string }; path: string[]; args: Record<string, string> };
    expect(payload.item.id).toBe('create-page');
    expect(payload.args).toEqual({ name: 'My Page', template: 'blank' });

    app.unmount();
  });

  it('argless non-regression: selecting a plain command still emits { item, path } with NO args key', async () => {
    const { app, host, selectPayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Plain command');
    selectRow(row);
    await nextTick();

    expect(host.querySelector('[data-testid="command-palette-args"]')).toBeNull();
    expect(selectPayloads.length).toBe(1);
    const payload = selectPayloads[0] as Record<string, unknown>;
    expect(payload).not.toHaveProperty('args');
    expect(payload.item).toMatchObject({ id: 'plain' });

    app.unmount();
  });

  it('required gating: Enter with a required field empty does NOT emit and focuses that field', async () => {
    const { app, host, selectPayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
    await nextTick();

    expect(selectPayloads.length).toBe(0);
    const nameInput = host.querySelectorAll('[data-command-palette-args] input')[0] as HTMLInputElement;
    expect(document.activeElement).toBe(nameInput);

    app.unmount();
  });

  it('default prefill: an arg with `default` opens with its input value pre-filled', async () => {
    const { app, host } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const templateInput = host.querySelectorAll('[data-command-palette-args] input')[1] as HTMLInputElement;
    expect(templateInput.value).toBe('blank');

    app.unmount();
  });

  it('Escape restores the list + query, focus back on the search input, and emits NEITHER @back NOR @navigate', async () => {
    const { app, host, navigatePayloads, backCount } = mountPalette();
    const input = await openPopup(host);
    input.value = 'crea';
    input.dispatchEvent(new Event('input', { bubbles: true }));
    await nextTick();

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    expect(host.querySelector('[data-testid="command-palette-args"]')).not.toBeNull();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }));
    await nextTick();
    await nextFrame();

    expect(host.querySelector('[data-testid="command-palette-args"]')).toBeNull();
    const listRegion = host.querySelector('.rozie-command-palette-list-region');
    expect(listRegion?.getAttribute('aria-hidden')).toBe('false');
    expect(navigatePayloads.length).toBe(0);
    expect(backCount.n).toBe(0);

    app.unmount();
  });

  it('Backspace on an empty first field returns to the list', async () => {
    const { app, host } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const nameInput = host.querySelectorAll('[data-command-palette-args] input')[0] as HTMLInputElement;
    nameInput.dispatchEvent(
      new KeyboardEvent('keydown', { key: 'Backspace', bubbles: true, cancelable: true }),
    );
    await nextTick();

    expect(host.querySelector('[data-testid="command-palette-args"]')).toBeNull();

    app.unmount();
  });

  it('#argsField override: a consumer slot fill renders custom chrome and its setValue still feeds the submit payload', async () => {
    const openRef = ref(true);
    const queryRef = ref('');
    const selectPayloads: unknown[] = [];
    const host = document.createElement('div');
    document.body.appendChild(host);
    hosts.push(host);
    const app = createApp({
      render: () =>
        h(
          CommandPalette,
          {
            open: openRef.value,
            'onUpdate:open': (v: boolean) => {
              openRef.value = v;
            },
            query: queryRef.value,
            'onUpdate:query': (v: string) => {
              queryRef.value = v;
            },
            items: makeItems(),
            idBase: 'args-behavior-slot-test',
            onSelect: (payload: unknown) => selectPayloads.push(payload),
          },
          {
            argsField: (scope: { arg: { id: string; placeholder?: string }; value: string; setValue: (v: string) => void }) =>
              h('input', {
                'data-testid': 'custom-args-field',
                'data-arg-id': scope.arg.id,
                value: scope.value,
                onInput: (e: Event) => scope.setValue((e.target as HTMLInputElement).value),
              }),
          },
        ),
    });
    app.mount(host);
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    const customFields = host.querySelectorAll('[data-testid="custom-args-field"]');
    expect(customFields.length).toBe(2);

    const nameField = customFields[0] as HTMLInputElement;
    nameField.value = 'Slotted Name';
    nameField.dispatchEvent(new Event('input', { bubbles: true }));
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
    await nextTick();

    expect(selectPayloads.length).toBe(1);
    const payload = selectPayloads[0] as { args: Record<string, string> };
    expect(payload.args.name).toBe('Slotted Name');

    app.unmount();
  });

  it('inert list: while args are active, a result-row click does NOT commit a @select', async () => {
    const { app, host, selectPayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Create page');
    selectRow(row);
    await nextTick();
    await nextFrame();

    expect(selectPayloads.length).toBe(0);

    const plainRow = optionRowFor(host, 'Plain command');
    selectRow(plainRow);
    await nextTick();

    expect(selectPayloads.length).toBe(0);
    expect(host.querySelector('[data-testid="command-palette-args"]')).not.toBeNull();

    app.unmount();
  });

  it('args × source: a source+args item enters the args surface (source ignored, no @navigate)', async () => {
    const { app, host, navigatePayloads } = mountPalette();
    await openPopup(host);

    const row = optionRowFor(host, 'Source and args');
    selectRow(row);
    await nextTick();
    await nextFrame();

    expect(host.querySelector('[data-testid="command-palette-args"]')).not.toBeNull();
    expect(navigatePayloads.length).toBe(0);

    app.unmount();
  });
});

/**
 * Finding 2 (SEV) — the args surface must not SELF-SUBMIT on the very Enter
 * that opens it. Chain: the vendored <Combobox>'s Enter commit
 * (Combobox.rozie onKeydown → selectOption → synchronous `@change`) preventDefaults
 * but does NOT stopPropagation, so onComboboxChange → openArgsSurface flips
 * activeSurface='args' SYNCHRONOUSLY (on the 5 non-React targets) and the SAME
 * keydown then bubbles to the frame's onPanelKeydown, whose args-branch fired
 * submitArgs() unconditionally on Enter — instantly @select-ing any command
 * whose args are already valid on open (a required arg with a `default`, or
 * all-optional args). RED-first against the pre-fix leaf.
 */
describe('CommandPalette args surface — opening Enter must not self-submit (finding 2, RED-first)', () => {
  // A required arg WITH a `default` → initArgValues prefills it → canSubmitArgs
  // is TRUE the instant the surface opens, so the buggy opening-Enter would
  // submit immediately. (create-page in makeItems has a required NO-default
  // `name`, so it would harmlessly focus-block — this fixture is what actually
  // exercises the self-submit.)
  function autoSubmitItems() {
    return [
      {
        id: 'defaulted',
        label: 'Defaulted',
        args: [{ id: 'name', placeholder: 'Name', required: true, default: 'preset' }],
      },
    ];
  }

  /**
   * Highlight the single row (combobox activates on @mouseenter) and press
   * Enter on the combobox input — the vendored <Combobox> commits the active
   * option on Enter (preventDefault, NO stopPropagation), and the SAME keydown
   * bubbles to the frame's onPanelKeydown.
   */
  async function highlightAndEnter(host: HTMLElement) {
    const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
    const row = optionRowFor(host, 'Defaulted');
    row.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
    await nextTick();
    input.dispatchEvent(
      new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }),
    );
    await nextTick();
    await nextFrame();
  }

  it('opening Enter OPENS the args surface and does NOT emit @select', async () => {
    const { app, host, selectPayloads } = mountPalette({ items: autoSubmitItems() });
    await openPopup(host);
    await highlightAndEnter(host);

    expect(host.querySelector('[data-testid="command-palette-args"]')).not.toBeNull();
    expect(selectPayloads.length).toBe(0);

    app.unmount();
  });

  it('a SECOND Enter (fields untouched, defaults valid) submits with the defaulted args', async () => {
    const { app, host, selectPayloads } = mountPalette({ items: autoSubmitItems() });
    await openPopup(host);
    await highlightAndEnter(host);
    // Let the opening-Enter guard disarm (a microtask) before the real submit.
    await Promise.resolve();
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));
    await nextTick();

    expect(selectPayloads.length).toBe(1);
    const payload = selectPayloads[0] as { item: { id: string }; args: Record<string, string> };
    expect(payload.item.id).toBe('defaulted');
    expect(payload.args).toEqual({ name: 'preset' });

    app.unmount();
  });

  it('Escape immediately after opening still exits (the guard must not eat Escape)', async () => {
    const { app, host, selectPayloads } = mountPalette({ items: autoSubmitItems() });
    await openPopup(host);
    await highlightAndEnter(host);
    expect(host.querySelector('[data-testid="command-palette-args"]')).not.toBeNull();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    frame.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true }));
    await nextTick();
    await nextFrame();

    expect(host.querySelector('[data-testid="command-palette-args"]')).toBeNull();
    expect(selectPayloads.length).toBe(0);

    app.unmount();
  });
});
