// @vitest-environment happy-dom
/**
 * groupcap-actions.behavior.test.ts — mount-and-drive behavioral proof that
 * `groupCap` composes correctly with per-row `actions` (260715-vkr).
 *
 * Root cause under test: the vendored <Combobox> assigns each rendered
 * option's DOM id from its CAPPED running index (cappedBlocks()'s `_i`, over
 * the whole visible+more sequence — Combobox.rozie ~468-495). Command-palette's
 * `highlightedItem()` (CommandPalette.rozie ~924-936) used to parse that same
 * index back out of the id and index into the UNCAPPED `orderedItems()` — the
 * two orderings diverge the moment any section overflows its cap, so the ⌘K /
 * Right-arrow action menu opened for the WRONG command (and could wrongly
 * open on a '+N more' row, which is not a command at all).
 *
 * Mirrors packages/ui/combobox/tests/group-cap.behavior.test.ts /
 * seed-query.behavior.test.ts: mount the REAL committed emitted
 * packages/vue/src/CommandPalette.vue (transformed by @vitejs/plugin-vue,
 * happy-dom supplies the DOM, the vendored @rozie-ui/combobox-vue supplies
 * the capped combobox render), drive it via real DOM events, and assert on
 * the rendered action-menu DOM.
 *
 * Fixture: groupCap: 2, two sections of 4 items each, every item carrying a
 * DISTINCT single action.
 *   Fruit: Apple, Banana, Cherry, Date
 *   Veg:   Carrot, Potato, Radish, Squash
 * Capped navRows sequence = [Apple(_i0), Banana(_i1), moreFruit(_i2),
 * Carrot(_i3), Potato(_i4), moreVeg(_i5)].
 *
 * Asserts:
 *   A. Highlighting Veg's 2nd VISIBLE row ("Potato", capped _i=4) and firing
 *      the action key (⌘K) opens the menu anchored to "Potato" — NOT
 *      "Carrot" (orderedItems()[4] in the UNCAPPED full list — the bug).
 *   B. Highlighting the '+N more' row (Veg's more-row, capped _i=5) and
 *      firing the action key is a no-op — no menu opens. (The bug resolved
 *      orderedItems()[5] === "Potato", a real command, and wrongly opened a
 *      menu for it.)
 *   C. Control (uncapped): with NO groupCap, highlighting "Potato" (in its
 *      normal uncapped position) and firing ⌘K opens the menu for "Potato" —
 *      proves the uncapped path is untouched.
 */
import { describe, it, expect, afterEach } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue leaf (regenerated by `node scripts/codegen.mjs`
// from CommandPalette.rozie) — @vitejs/plugin-vue transforms this SFC into a
// mountable component.
import CommandPalette from '../packages/vue/src/CommandPalette.vue';

function makeItems() {
  return [
    { id: 'apple', label: 'Apple', group: 'Fruit', actions: [{ id: 'apple-act', label: 'Apple action' }] },
    { id: 'banana', label: 'Banana', group: 'Fruit', actions: [{ id: 'banana-act', label: 'Banana action' }] },
    { id: 'cherry', label: 'Cherry', group: 'Fruit', actions: [{ id: 'cherry-act', label: 'Cherry action' }] },
    { id: 'date', label: 'Date', group: 'Fruit', actions: [{ id: 'date-act', label: 'Date action' }] },
    { id: 'carrot', label: 'Carrot', group: 'Veg', actions: [{ id: 'carrot-act', label: 'Carrot action' }] },
    { id: 'potato', label: 'Potato', group: 'Veg', actions: [{ id: 'potato-act', label: 'Potato action' }] },
    { id: 'radish', label: 'Radish', group: 'Veg', actions: [{ id: 'radish-act', label: 'Radish action' }] },
    { id: 'squash', label: 'Squash', group: 'Veg', actions: [{ id: 'squash-act', label: 'Squash action' }] },
  ];
}

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount CommandPalette, seeded `open: true`, two-way `open`/`query` bound via
 * refs. Returns the host element.
 */
function mountPalette(extraProps: Record<string, unknown> = {}) {
  const openRef = ref(true);
  const queryRef = ref('');
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(CommandPalette, {
        open: openRef.value,
        'onUpdate:open': (v: boolean) => {
          openRef.value = v;
        },
        query: queryRef.value,
        'onUpdate:query': (v: string) => {
          queryRef.value = v;
        },
        items: makeItems(),
        idBase: 'groupcap-actions-test',
        ...extraProps,
      }),
  });
  app.mount(host);
  return { app, host };
}

/** Focus the combobox's search input (opens the popup) and flush. */
async function openPopup(host: HTMLElement) {
  const input = host.querySelector('input[role="combobox"]') as HTMLInputElement;
  input.dispatchEvent(new Event('focus'));
  await nextTick();
  await Promise.resolve();
  return input;
}

/** The actionKey default is `$mod+k` — ⌘K on the DOM-event-matcher shape. */
function fireActionKey(target: Element) {
  target.dispatchEvent(
    new KeyboardEvent('keydown', { key: 'k', metaKey: true, bubbles: true, cancelable: true }),
  );
}

describe('CommandPalette groupCap × per-row actions composition (behavioral)', () => {
  it('A: highlighting the 2nd VISIBLE row of a capped section opens the menu for THAT EXACT command, never the uncapped-order neighbour', async () => {
    const { app, host } = mountPalette({ groupCap: 2 });
    await openPopup(host);

    const groups = host.querySelectorAll('[role="group"]');
    expect(groups.length).toBe(2);

    const vegVisible = groups[1]!.querySelectorAll('[role="option"]:not(.rozie-combobox-more)');
    expect(vegVisible.length).toBe(2);
    const potatoRow = vegVisible[1] as HTMLElement;
    expect(potatoRow.textContent).toContain('Potato');

    potatoRow.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    fireActionKey(frame);
    await nextTick();

    const menu = host.querySelector('[data-command-palette-menu]');
    expect(menu).not.toBeNull();
    // CURRENT (buggy) source resolves orderedItems()[4] in the UNCAPPED list
    // = "Carrot" — this assertion is the RED proof.
    expect(menu!.getAttribute('aria-label')).toBe('Potato');

    app.unmount();
  });

  it("B: highlighting a '+N more' row and firing the action key is a no-op — no action menu opens", async () => {
    const { app, host } = mountPalette({ groupCap: 2 });
    await openPopup(host);

    const groups = host.querySelectorAll('[role="group"]');
    const vegMore = groups[1]!.querySelector('.rozie-combobox-more') as HTMLElement;
    expect(vegMore).not.toBeNull();

    vegMore.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    fireActionKey(frame);
    await nextTick();

    // CURRENT (buggy) source resolves orderedItems()[5] in the UNCAPPED list
    // = "Potato" (a real command with actions) — a menu WRONGLY opens. This
    // assertion (no menu) is the RED proof.
    expect(host.querySelector('[data-command-palette-menu]')).toBeNull();

    app.unmount();
  });

  it('C (control): with NO groupCap, highlighting Potato and firing the action key opens the menu for Potato — uncapped path untouched', async () => {
    const { app, host } = mountPalette();
    await openPopup(host);

    const potatoRow = Array.from(host.querySelectorAll('[role="option"]')).find((el) =>
      el.textContent?.includes('Potato'),
    ) as HTMLElement;
    expect(potatoRow).toBeTruthy();

    potatoRow.dispatchEvent(new MouseEvent('mouseenter', { bubbles: true }));
    await nextTick();

    const frame = host.querySelector('[data-testid="command-palette-frame"]') as HTMLElement;
    fireActionKey(frame);
    await nextTick();

    const menu = host.querySelector('[data-command-palette-menu]');
    expect(menu).not.toBeNull();
    expect(menu!.getAttribute('aria-label')).toBe('Potato');

    app.unmount();
  });
});
