/**
 * model-param-shadow.vue.test.ts — behavioral proof for the Phase-57 Vue
 * param-vs-bare-ref deconflict (SC-5 behavioral half).
 *
 * THE BUG CLASS (broadened from the captcha @defineModel slice): a closure/
 * callback param that shares the name of a Vue same-named GENERATED bare ref —
 * a `model: true` prop (`defineModel('token')`), a `$data` key (`ref(...)`), or
 * a `$computed` name (`computed(...)`) — silently SHADOWS the generated ref. The
 * pre-fix Vue lowering emitted `token.value = token` / `status.value = status`,
 * which writes the PARAM (a no-op on the ref) → `v-model:token` never populates
 * and the `$data`-backed binding never refreshes. It compiles + typechecks clean
 * (a runtime semantic bug), so only a mount-and-drive test catches it.
 *
 * We mount the REAL emitted ModelParamShadow.vue (the committed dist-parity
 * fixture, transformed by @vitejs/plugin-vue — reusing captcha's already-present
 * vue harness per Phase-57 threat model T-57-SC, no new package installs) under a
 * parent that binds v-model:token, drive the template-wired closures by clicking
 * the rendered buttons, and assert BOTH the two-way `token` model AND the
 * `$data.status` binding update through the renamed `<name>$local` params.
 *
 * NON-VACUOUS (executor-confirmed RED-without-fix): with the Task-2 Vue
 * deconflict groups stubbed out, the bootstrap re-emits this fixture with
 * `token.value = token` and `status.value = status` (the param self-writes). The
 * executor temporarily reverted the `deconflictGeneratedSymbols(program,
 * vueGroups, ...)` call in packages/targets/vue/src/rewrite/rewriteScript.ts,
 * rebuilt core+vue, re-bootstrapped, and observed BOTH `it(...)` cases below go
 * RED (token stayed '', the status span never showed 'ready'); restoring the
 * groups returns them GREEN. The byte-level RED was also captured in Task 1
 * (commit 552e49fb): the pre-fix emit was `token.value = token` /
 * `status.value = status` / `label.value`.
 */
import { describe, it, expect, afterEach, vi } from 'vitest';
import { createApp, h, ref, nextTick } from 'vue';
// The committed emitted Vue output (generated by `pnpm --filter dist-parity
// bootstrap` against the fixed emitter). plugin-vue transforms this SFC into a
// mountable component.
import ModelParamShadow from '../../../../tests/dist-parity/fixtures/ModelParamShadow.vue';

const hosts: HTMLElement[] = [];

afterEach(() => {
  for (const host of hosts.splice(0)) host.remove();
});

/**
 * Mount ModelParamShadow under a parent that binds v-model:token, returning the
 * live parent `token` ref, the collected `verify` events, and the host element
 * (for querying the rendered $data.status text).
 */
function mountShadow() {
  const token = ref('');
  const verify: Array<Record<string, unknown>> = [];
  const host = document.createElement('div');
  document.body.appendChild(host);
  hosts.push(host);
  const app = createApp({
    render: () =>
      h(ModelParamShadow, {
        token: token.value,
        'onUpdate:token': (v: string) => {
          token.value = v;
        },
        onVerify: (e: Record<string, unknown>) => verify.push(e),
      }),
  });
  app.mount(host);
  return { app, token, verify, host };
}

/** Click the rendered button whose text content matches `label`. */
function clickButton(host: HTMLElement, label: string) {
  const btn = [...host.querySelectorAll('button')].find(
    (b) => b.textContent?.trim() === label,
  );
  if (!btn) throw new Error(`button "${label}" not found in mounted output`);
  btn.dispatchEvent(new Event('click', { bubbles: true }));
}

describe('ModelParamShadow (vue) — param-vs-bare-ref deconflict regression', () => {
  it('populates v-model:token through the renamed model-shadowing param', async () => {
    const { app, token, verify, host } = mountShadow();

    clickButton(host, 'solve'); // solve('demo-token') → token.value = token$local

    // The bug: token stayed '' (the defineModel ref was shadowed by the param).
    await vi.waitFor(() => expect(token.value).toBe('demo-token'));
    expect(verify.at(-1)).toMatchObject({ token: 'demo-token' });
    app.unmount();
  });

  it('updates the $data.status binding through the renamed data-shadowing param', async () => {
    const { app, host } = mountShadow();

    clickButton(host, 'status'); // setStatus('ready') → status.value = status$local
    await nextTick();

    // The bug: status stayed '' (the state ref was shadowed by the param), so
    // the rendered <span class="status"> never showed 'ready'.
    await vi.waitFor(() =>
      expect(host.querySelector('.status')?.textContent).toContain('ready'),
    );
    app.unmount();
  });
});
