/**
 * Self-contained mirror of the emitted `@rozie-ui/flatpickr-react` typed
 * contract — the AUTHORITY is
 * `packages/ui/flatpickr/packages/react/src/Flatpickr.d.ts` (regenerated by
 * `packages/ui/flatpickr/scripts/codegen.mjs`). This probe fixture mirrors the
 * load-bearing `name?: string` field of `FlatpickrProps` so the forms-drop-in
 * (GAP-1) contract can be type-asserted here without wiring the leaf package's
 * emitted `.d.ts` into this probe's tsconfig include (it lives outside this
 * project's `include` glob). If the emitted shape changes, update this mirror.
 */
import type { ForwardRefExoticComponent, RefAttributes } from 'react';

export interface FlatpickrProps {
  date?: string;
  defaultDate?: string;
  onDateChange?: (next: string) => void;
  mode?: string;
  dateFormat?: string;
  altInput?: boolean;
  altFormat?: string;
  enableTime?: boolean;
  enableSeconds?: boolean;
  time24hr?: boolean;
  noCalendar?: boolean;
  minDate?: string | null;
  maxDate?: string | null;
  placeholder?: string;
  disabled?: boolean;
  commitOn?: string;
  options?: Record<string, unknown>;
  // GAP-1 — forms drop-in.
  name?: string;
  // GAP-5 — UI passthrough.
  inline?: boolean;
  static?: boolean;
  position?: string;
  appendTo?: Record<string, unknown> | null;
  showMonths?: number;
  weekNumbers?: boolean;
  monthSelectorType?: string;
  prevArrow?: string | null;
  nextArrow?: string | null;
  // GAP-6a.
  allowInput?: boolean;
  // GAP-2/3/4/6b.
  disable?: unknown[];
  enable?: unknown[];
  locale?: Record<string, unknown> | null;
  firstDayOfWeek?: number;
  parseDate?: ((...args: unknown[]) => unknown) | null;
  formatDate?: ((...args: unknown[]) => unknown) | null;
  plugins?: unknown[];
  onChange?: (...args: unknown[]) => void;
  onReady?: (...args: unknown[]) => void;
  onOpen?: (...args: unknown[]) => void;
  onClose?: (...args: unknown[]) => void;
  onMonthChange?: (...args: unknown[]) => void;
  onYearChange?: (...args: unknown[]) => void;
  onValueUpdate?: (...args: unknown[]) => void;
  onDayCreate?: (...args: unknown[]) => void;
}

export interface FlatpickrHandle {
  clear: (...args: any[]) => any;
  openPicker: (...args: any[]) => any;
  closePicker: (...args: any[]) => any;
  selectDate: (...args: any[]) => any;
  jumpToDate: (...args: any[]) => any;
}

declare const Flatpickr: ForwardRefExoticComponent<
  FlatpickrProps & RefAttributes<FlatpickrHandle>
>;
export default Flatpickr;
