/**
 * Self-contained mirror of the emitted `@rozie-ui/flatpickr-angular`
 * signal-era typed `name` input — the AUTHORITY is
 * `packages/ui/flatpickr/packages/angular/src/Flatpickr.ts` (regenerated by
 * `packages/ui/flatpickr/scripts/codegen.mjs`), where the emitted class
 * declares `name = input<string>('')`.
 *
 * We mirror ONLY the `name` input (plus the `date` model) rather than importing
 * the full emitted leaf — the leaf imports `flatpickr` at module top, which is
 * not a dep of this type-only probe project. The contract under test is purely
 * the signal-input TYPE, so a faithful mirror of the relevant member suffices.
 * If the emitted `name` factory ever changes, update this mirror.
 */
import { Component, input, model } from '@angular/core';

@Component({
  selector: 'rozie-flatpickr',
  standalone: true,
  template: `<input [name]="name()" />`,
})
export class FlatpickrName {
  date = model<string>('');
  // GAP-1 — forms drop-in. Signal-era typed input (input<string>).
  name = input<string>('');
}
